
package com.nortel.soa.oi.cct.routepointaddressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:03:59.281+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "ControlException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class ControlException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo controlException;

    public ControlException() {
        super();
    }
    
    public ControlException(String message) {
        super(message);
    }
    
    public ControlException(String message, Throwable cause) {
        super(message, cause);
    }

    public ControlException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo controlException) {
        super(message);
        this.controlException = controlException;
    }

    public ControlException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo controlException, Throwable cause) {
        super(message, cause);
        this.controlException = controlException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.controlException;
    }
}
