package com.nortel.soa.oi.cct.routepointaddressservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:03:59.312+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/RoutePointAddressService", name = "RoutePointAddressService")
@XmlSeeAlso({com.nortel.soa.oi.cct.types.routepointaddressservice.ObjectFactory.class, com.nortel.soa.oi.cct.faults.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RoutePointAddressService {

    @WebMethod(operationName = "ReleaseControl", action = "http://www.nortel.com/soa/oi/cct/RoutePointAddressService/ReleaseControl")
    public void releaseControl(
        @WebParam(partName = "parameters", name = "ReleaseControlRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointAddressService")
        com.nortel.soa.oi.cct.types.routepointaddressservice.RoutePointAddressRequest parameters
    ) throws ReleaseControlException, SessionNotCreatedException;

    @WebResult(name = "IsControlledResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointAddressService", partName = "result")
    @WebMethod(operationName = "IsControlled", action = "http://www.nortel.com/soa/oi/cct/RoutePointAddressService/IsControlled")
    public com.nortel.soa.oi.cct.types.routepointaddressservice.BooleanResponse isControlled(
        @WebParam(partName = "parameters", name = "IsControlledRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointAddressService")
        com.nortel.soa.oi.cct.types.routepointaddressservice.RoutePointAddressRequest parameters
    ) throws IsControlledException, SessionNotCreatedException;

    @WebMethod(operationName = "Control", action = "http://www.nortel.com/soa/oi/cct/RoutePointAddressService/Control")
    public void control(
        @WebParam(partName = "parameters", name = "ControlRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointAddressService")
        com.nortel.soa.oi.cct.types.routepointaddressservice.RoutePointAddressRequest parameters
    ) throws ControlException, SessionNotCreatedException;

    @WebResult(name = "GetVersionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointAddressService", partName = "response")
    @WebMethod(operationName = "GetVersion", action = "http://www.nortel.com/soa/oi/cct/RoutePointAddressService/GetVersion")
    public com.nortel.soa.oi.cct.types.GetVersionResponse getVersion(
        @WebParam(partName = "parameters", name = "GetVersionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointAddressService")
        com.nortel.soa.oi.cct.types.GetVersionRequest parameters
    ) throws SessionNotCreatedException, GetVersionException;
}
