
package com.nortel.soa.oi.cct.terminalservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:43.671+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetDefaultContactTypeException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetDefaultContactTypeException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getDefaultContactTypeException;

    public GetDefaultContactTypeException() {
        super();
    }
    
    public GetDefaultContactTypeException(String message) {
        super(message);
    }
    
    public GetDefaultContactTypeException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetDefaultContactTypeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getDefaultContactTypeException) {
        super(message);
        this.getDefaultContactTypeException = getDefaultContactTypeException;
    }

    public GetDefaultContactTypeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getDefaultContactTypeException, Throwable cause) {
        super(message, cause);
        this.getDefaultContactTypeException = getDefaultContactTypeException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getDefaultContactTypeException;
    }
}
