
package com.nortel.soa.oi.cct.terminalservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:43.562+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "PickupException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class PickupException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo pickupException;

    public PickupException() {
        super();
    }
    
    public PickupException(String message) {
        super(message);
    }
    
    public PickupException(String message, Throwable cause) {
        super(message, cause);
    }

    public PickupException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo pickupException) {
        super(message);
        this.pickupException = pickupException;
    }

    public PickupException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo pickupException, Throwable cause) {
        super(message, cause);
        this.pickupException = pickupException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.pickupException;
    }
}
