package com.nortel.soa.oi.cct.metricsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:53.781+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/MetricsService", name = "MetricsService")
@XmlSeeAlso({com.nortel.soa.oi.cct.types.metricsservice.ObjectFactory.class, com.nortel.soa.oi.cct.faults.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MetricsService {

    @WebResult(name = "GetActiveSessionCountResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/MetricsService", partName = "result")
    @WebMethod(operationName = "GetActiveSessionCount", action = "http://www.nortel.com/soa/oi/cct/MetricsService/GetActiveSessionCount")
    public com.nortel.soa.oi.cct.types.metricsservice.MetricsResponse getActiveSessionCount(
        @WebParam(partName = "parameters", name = "GetActiveSessionCountRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/MetricsService")
        com.nortel.soa.oi.cct.types.metricsservice.MetricsRequest parameters
    ) throws MonitoredAddressesCountException, SessionNotCreatedException;

    @WebResult(name = "GetMonitoredAddressCountResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/MetricsService", partName = "result")
    @WebMethod(operationName = "GetMonitoredAddressCount", action = "http://www.nortel.com/soa/oi/cct/MetricsService/GetMonitoredAddressCount")
    public com.nortel.soa.oi.cct.types.metricsservice.MetricsResponse getMonitoredAddressCount(
        @WebParam(partName = "parameters", name = "GetMonitoredAddressCountRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/MetricsService")
        com.nortel.soa.oi.cct.types.metricsservice.MetricsRequest parameters
    ) throws MonitoredAddressesCountException, SessionNotCreatedException;

    @WebResult(name = "GetLicenseConsumedCountResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/MetricsService", partName = "result")
    @WebMethod(operationName = "GetLicenseConsumedCount", action = "http://www.nortel.com/soa/oi/cct/MetricsService/GetLicenseConsumedCount")
    public com.nortel.soa.oi.cct.types.metricsservice.MetricsResponse getLicenseConsumedCount(
        @WebParam(partName = "parameters", name = "GetLicenseConsumedCountRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/MetricsService")
        com.nortel.soa.oi.cct.types.metricsservice.MetricsRequest parameters
    ) throws MonitoredAddressesCountException, SessionNotCreatedException;

    @WebResult(name = "GetVersionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/MetricsService", partName = "result")
    @WebMethod(operationName = "GetVersion", action = "http://www.nortel.com/soa/oi/cct/MetricsService/GetVersion")
    public com.nortel.soa.oi.cct.types.GetVersionResponse getVersion(
        @WebParam(partName = "parameters", name = "GetVersionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/MetricsService")
        com.nortel.soa.oi.cct.types.GetVersionRequest parameters
    ) throws SessionNotCreatedException, GetVersionException;

    @WebResult(name = "GetMonitoredTerminalsResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/MetricsService", partName = "result")
    @WebMethod(operationName = "GetMonitoredTerminalsCount", action = "http://www.nortel.com/soa/oi/cct/MetricsService/GetMonitoredTerminalsCount")
    public com.nortel.soa.oi.cct.types.metricsservice.MetricsResponse getMonitoredTerminalsCount(
        @WebParam(partName = "parameters", name = "GetMonitoredTerminalsRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/MetricsService")
        com.nortel.soa.oi.cct.types.metricsservice.MetricsRequest parameters
    ) throws MonitoredTerminalsCountException, SessionNotCreatedException;
}
