
package com.nortel.soa.oi.cct.metricsservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:53.640+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "MonitoredAddressesCountException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class MonitoredAddressesCountException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo monitoredAddressesCountException;

    public MonitoredAddressesCountException() {
        super();
    }
    
    public MonitoredAddressesCountException(String message) {
        super(message);
    }
    
    public MonitoredAddressesCountException(String message, Throwable cause) {
        super(message, cause);
    }

    public MonitoredAddressesCountException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo monitoredAddressesCountException) {
        super(message);
        this.monitoredAddressesCountException = monitoredAddressesCountException;
    }

    public MonitoredAddressesCountException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo monitoredAddressesCountException, Throwable cause) {
        super(message, cause);
        this.monitoredAddressesCountException = monitoredAddressesCountException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.monitoredAddressesCountException;
    }
}
