
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:23.953+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "AnswerContactException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class AnswerContactException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo answerContactException;

    public AnswerContactException() {
        super();
    }
    
    public AnswerContactException(String message) {
        super(message);
    }
    
    public AnswerContactException(String message, Throwable cause) {
        super(message, cause);
    }

    public AnswerContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo answerContactException) {
        super(message);
        this.answerContactException = answerContactException;
    }

    public AnswerContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo answerContactException, Throwable cause) {
        super(message, cause);
        this.answerContactException = answerContactException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.answerContactException;
    }
}
