
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:23.875+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "CallSupervisorException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class CallSupervisorException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo callSupervisorException;

    public CallSupervisorException() {
        super();
    }
    
    public CallSupervisorException(String message) {
        super(message);
    }
    
    public CallSupervisorException(String message, Throwable cause) {
        super(message, cause);
    }

    public CallSupervisorException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo callSupervisorException) {
        super(message);
        this.callSupervisorException = callSupervisorException;
    }

    public CallSupervisorException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo callSupervisorException, Throwable cause) {
        super(message, cause);
        this.callSupervisorException = callSupervisorException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.callSupervisorException;
    }
}
