
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.015+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "DisposeException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class DisposeException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo disposeException;

    public DisposeException() {
        super();
    }
    
    public DisposeException(String message) {
        super(message);
    }
    
    public DisposeException(String message, Throwable cause) {
        super(message, cause);
    }

    public DisposeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo disposeException) {
        super(message);
        this.disposeException = disposeException;
    }

    public DisposeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo disposeException, Throwable cause) {
        super(message, cause);
        this.disposeException = disposeException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.disposeException;
    }
}
