
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:23.937+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "DropContactException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class DropContactException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo dropContactException;

    public DropContactException() {
        super();
    }
    
    public DropContactException(String message) {
        super(message);
    }
    
    public DropContactException(String message, Throwable cause) {
        super(message, cause);
    }

    public DropContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo dropContactException) {
        super(message);
        this.dropContactException = dropContactException;
    }

    public DropContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo dropContactException, Throwable cause) {
        super(message, cause);
        this.dropContactException = dropContactException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.dropContactException;
    }
}
