
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.078+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GenerateDTMFException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GenerateDTMFException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo generateDTMFException;

    public GenerateDTMFException() {
        super();
    }
    
    public GenerateDTMFException(String message) {
        super(message);
    }
    
    public GenerateDTMFException(String message, Throwable cause) {
        super(message, cause);
    }

    public GenerateDTMFException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo generateDTMFException) {
        super(message);
        this.generateDTMFException = generateDTMFException;
    }

    public GenerateDTMFException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo generateDTMFException, Throwable cause) {
        super(message, cause);
        this.generateDTMFException = generateDTMFException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.generateDTMFException;
    }
}
