
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:23.984+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetAgentTerminalsException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetAgentTerminalsException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAgentTerminalsException;

    public GetAgentTerminalsException() {
        super();
    }
    
    public GetAgentTerminalsException(String message) {
        super(message);
    }
    
    public GetAgentTerminalsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAgentTerminalsException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAgentTerminalsException) {
        super(message);
        this.getAgentTerminalsException = getAgentTerminalsException;
    }

    public GetAgentTerminalsException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAgentTerminalsException, Throwable cause) {
        super(message, cause);
        this.getAgentTerminalsException = getAgentTerminalsException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getAgentTerminalsException;
    }
}
