
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.062+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetAgentAddressesException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetAgentAddressesException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAgentAddressesException;

    public GetAgentAddressesException() {
        super();
    }
    
    public GetAgentAddressesException(String message) {
        super(message);
    }
    
    public GetAgentAddressesException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAgentAddressesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAgentAddressesException) {
        super(message);
        this.getAgentAddressesException = getAgentAddressesException;
    }

    public GetAgentAddressesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAgentAddressesException, Throwable cause) {
        super(message, cause);
        this.getAgentAddressesException = getAgentAddressesException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getAgentAddressesException;
    }
}
