
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.187+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetContactDataException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetContactDataException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactDataException;

    public GetContactDataException() {
        super();
    }
    
    public GetContactDataException(String message) {
        super(message);
    }
    
    public GetContactDataException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContactDataException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactDataException) {
        super(message);
        this.getContactDataException = getContactDataException;
    }

    public GetContactDataException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactDataException, Throwable cause) {
        super(message, cause);
        this.getContactDataException = getContactDataException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getContactDataException;
    }
}
