
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:23.968+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetCurrentTerminalCountException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetCurrentTerminalCountException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getCurrentTerminalCountException;

    public GetCurrentTerminalCountException() {
        super();
    }
    
    public GetCurrentTerminalCountException(String message) {
        super(message);
    }
    
    public GetCurrentTerminalCountException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetCurrentTerminalCountException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getCurrentTerminalCountException) {
        super(message);
        this.getCurrentTerminalCountException = getCurrentTerminalCountException;
    }

    public GetCurrentTerminalCountException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getCurrentTerminalCountException, Throwable cause) {
        super(message, cause);
        this.getCurrentTerminalCountException = getCurrentTerminalCountException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getCurrentTerminalCountException;
    }
}
