
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.234+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetIntrinsicsException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetIntrinsicsException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getIntrinsicsException;

    public GetIntrinsicsException() {
        super();
    }
    
    public GetIntrinsicsException(String message) {
        super(message);
    }
    
    public GetIntrinsicsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetIntrinsicsException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getIntrinsicsException) {
        super(message);
        this.getIntrinsicsException = getIntrinsicsException;
    }

    public GetIntrinsicsException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getIntrinsicsException, Throwable cause) {
        super(message, cause);
        this.getIntrinsicsException = getIntrinsicsException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getIntrinsicsException;
    }
}
