
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:23.906+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetReadyStateException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetReadyStateException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getReadyStateException;

    public GetReadyStateException() {
        super();
    }
    
    public GetReadyStateException(String message) {
        super(message);
    }
    
    public GetReadyStateException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetReadyStateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getReadyStateException) {
        super(message);
        this.getReadyStateException = getReadyStateException;
    }

    public GetReadyStateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getReadyStateException, Throwable cause) {
        super(message, cause);
        this.getReadyStateException = getReadyStateException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getReadyStateException;
    }
}
