
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.125+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetTerminalAddressesException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetTerminalAddressesException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalAddressesException;

    public GetTerminalAddressesException() {
        super();
    }
    
    public GetTerminalAddressesException(String message) {
        super(message);
    }
    
    public GetTerminalAddressesException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTerminalAddressesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalAddressesException) {
        super(message);
        this.getTerminalAddressesException = getTerminalAddressesException;
    }

    public GetTerminalAddressesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalAddressesException, Throwable cause) {
        super(message, cause);
        this.getTerminalAddressesException = getTerminalAddressesException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getTerminalAddressesException;
    }
}
