
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.203+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "InitiateSupervisedTransferException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class InitiateSupervisedTransferException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo initiateSupervisedTransferException;

    public InitiateSupervisedTransferException() {
        super();
    }
    
    public InitiateSupervisedTransferException(String message) {
        super(message);
    }
    
    public InitiateSupervisedTransferException(String message, Throwable cause) {
        super(message, cause);
    }

    public InitiateSupervisedTransferException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo initiateSupervisedTransferException) {
        super(message);
        this.initiateSupervisedTransferException = initiateSupervisedTransferException;
    }

    public InitiateSupervisedTransferException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo initiateSupervisedTransferException, Throwable cause) {
        super(message, cause);
        this.initiateSupervisedTransferException = initiateSupervisedTransferException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.initiateSupervisedTransferException;
    }
}
