
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.046+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "LoginAgentToStateException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class LoginAgentToStateException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo loginAgentToStateException;

    public LoginAgentToStateException() {
        super();
    }
    
    public LoginAgentToStateException(String message) {
        super(message);
    }
    
    public LoginAgentToStateException(String message, Throwable cause) {
        super(message, cause);
    }

    public LoginAgentToStateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo loginAgentToStateException) {
        super(message);
        this.loginAgentToStateException = loginAgentToStateException;
    }

    public LoginAgentToStateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo loginAgentToStateException, Throwable cause) {
        super(message, cause);
        this.loginAgentToStateException = loginAgentToStateException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.loginAgentToStateException;
    }
}
