
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.093+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "LoginAgentToTerminalException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class LoginAgentToTerminalException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo loginAgentToTerminalException;

    public LoginAgentToTerminalException() {
        super();
    }
    
    public LoginAgentToTerminalException(String message) {
        super(message);
    }
    
    public LoginAgentToTerminalException(String message, Throwable cause) {
        super(message, cause);
    }

    public LoginAgentToTerminalException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo loginAgentToTerminalException) {
        super(message);
        this.loginAgentToTerminalException = loginAgentToTerminalException;
    }

    public LoginAgentToTerminalException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo loginAgentToTerminalException, Throwable cause) {
        super(message, cause);
        this.loginAgentToTerminalException = loginAgentToTerminalException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.loginAgentToTerminalException;
    }
}
