
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.203+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "LogoutAgentException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class LogoutAgentException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo logoutAgentException;

    public LogoutAgentException() {
        super();
    }
    
    public LogoutAgentException(String message) {
        super(message);
    }
    
    public LogoutAgentException(String message, Throwable cause) {
        super(message, cause);
    }

    public LogoutAgentException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo logoutAgentException) {
        super(message);
        this.logoutAgentException = logoutAgentException;
    }

    public LogoutAgentException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo logoutAgentException, Throwable cause) {
        super(message, cause);
        this.logoutAgentException = logoutAgentException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.logoutAgentException;
    }
}
