package com.nortel.soa.oi.cct.sessionservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.250+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/SessionService", name = "SessionService")
@XmlSeeAlso({com.nortel.soa.oi.cct.types.sessionservice.ObjectFactory.class, com.nortel.soa.oi.cct.faults.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SessionService {

    @WebResult(name = "InitiateConferenceResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "InitiateConference", action = "http://www.nortel.com/soa/oi/cct/SessionService/InitiateConference")
    public com.nortel.soa.oi.cct.types.sessionservice.ContactResponse initiateConference(
        @WebParam(partName = "parameters", name = "InitiateConferenceRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalContactAddressRequest parameters
    ) throws InitiateConferenceException, SessionNotCreatedException;

    @WebMethod(operationName = "CallSupervisor", action = "http://www.nortel.com/soa/oi/cct/SessionService/CallSupervisor")
    public void callSupervisor(
        @WebParam(partName = "parameters", name = "CallSupervisorRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalAddressRequest parameters
    ) throws CallSupervisorException, SessionNotCreatedException;

    @WebResult(name = "GetReadyStateResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "parameters")
    @WebMethod(operationName = "GetReadyState", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetReadyState")
    public com.nortel.soa.oi.cct.types.sessionservice.GetReadyStateResponse getReadyState(
        @WebParam(partName = "parameters", name = "GetReadyStateRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalRequest parameters
    ) throws SessionNotCreatedException, GetReadyStateException;

    @WebResult(name = "GetVersionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "response")
    @WebMethod(operationName = "GetVersion", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetVersion")
    public com.nortel.soa.oi.cct.types.GetVersionResponse getVersion(
        @WebParam(partName = "parameters", name = "GetVersionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.GetVersionRequest parameters
    ) throws SessionNotCreatedException, GetVersionException;

    @WebMethod(operationName = "DropContact", action = "http://www.nortel.com/soa/oi/cct/SessionService/DropContact")
    public void dropContact(
        @WebParam(partName = "parameters", name = "DropContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalContactRequest parameters
    ) throws DropContactException, SessionNotCreatedException;

    @WebMethod(operationName = "CompleteSupervisedTransfer", action = "http://www.nortel.com/soa/oi/cct/SessionService/CompleteSupervisedTransfer")
    public void completeSupervisedTransfer(
        @WebParam(partName = "parameters", name = "CompleteSupervisedTransferRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalContactContactRequest parameters
    ) throws CompleteSupervisedTransferException, SessionNotCreatedException;

    @WebMethod(operationName = "AnswerContact", action = "http://www.nortel.com/soa/oi/cct/SessionService/AnswerContact")
    public void answerContact(
        @WebParam(partName = "parameters", name = "AnswerContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalContactRequest parameters
    ) throws AnswerContactException, SessionNotCreatedException;

    @WebMethod(operationName = "LoginAgent", action = "http://www.nortel.com/soa/oi/cct/SessionService/LoginAgent")
    public void loginAgent(
        @WebParam(partName = "parameters", name = "LoginAgentRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.LoginAgentRequest parameters
    ) throws LoginAgentException, SessionNotCreatedException;

    @WebResult(name = "GetCurrentTerminalCountResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "response")
    @WebMethod(operationName = "GetCurrentTerminalCount", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetCurrentTerminalCount")
    public int getCurrentTerminalCount(
        @WebParam(partName = "parameters", name = "GetCurrentTerminalCountRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.SsoRequest parameters
    ) throws GetCurrentTerminalCountException, SessionNotCreatedException;

    @WebMethod(operationName = "SetToNotReadyStateWithReasonCode", action = "http://www.nortel.com/soa/oi/cct/SessionService/SetToNotReadyStateWithReasonCode")
    public void setToNotReadyStateWithReasonCode(
        @WebParam(partName = "parameters", name = "SetToNotReadyStateWithReasonCodeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.SetToNotReadyStateWithReasonCodeRequest parameters
    ) throws SetToNotReadyStateWithReasonCodeException, SessionNotCreatedException;

    @WebResult(name = "GetAgentTerminalsResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "GetAgentTerminals", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetAgentTerminals")
    public com.nortel.soa.oi.cct.types.sessionservice.TerminalList getAgentTerminals(
        @WebParam(partName = "parameters", name = "GetAgentTerminalsRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.GetAgentTerminalsRequest parameters
    ) throws SessionNotCreatedException, GetAgentTerminalsException;

    @WebMethod(operationName = "SetIntrinsics", action = "http://www.nortel.com/soa/oi/cct/SessionService/SetIntrinsics")
    public void setIntrinsics(
        @WebParam(partName = "parameters", name = "SetIntrinsicsRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.SetIntrinsicsRequest parameters
    ) throws SetIntrinsicsException, SessionNotCreatedException;

    @WebMethod(operationName = "UnHoldContact", action = "http://www.nortel.com/soa/oi/cct/SessionService/UnHoldContact")
    public void unHoldContact(
        @WebParam(partName = "parameters", name = "UnHoldContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalContactRequest parameters
    ) throws UnHoldContactException, SessionNotCreatedException;

    @WebMethod(operationName = "Dispose", action = "http://www.nortel.com/soa/oi/cct/SessionService/Dispose")
    public void dispose(
        @WebParam(partName = "parameters", name = "DisposeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.SsoRequest parameters
    ) throws DisposeException, SessionNotCreatedException;

    @WebMethod(operationName = "LogoutAgentFromTerminal", action = "http://www.nortel.com/soa/oi/cct/SessionService/LogoutAgentFromTerminal")
    public void logoutAgentFromTerminal(
        @WebParam(partName = "parameters", name = "LogoutAgentFromTerminalRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.LogoutAgentFromTerminalRequest parameters
    ) throws LogoutAgentFromTerminalException, SessionNotCreatedException;

    @WebMethod(operationName = "LoginAgentToState", action = "http://www.nortel.com/soa/oi/cct/SessionService/LoginAgentToState")
    public void loginAgentToState(
        @WebParam(partName = "parameters", name = "LoginAgentToStateRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.LoginAgentToStateRequest parameters
    ) throws LoginAgentToStateException, SessionNotCreatedException;

    @WebMethod(operationName = "MakeSetBusy", action = "http://www.nortel.com/soa/oi/cct/SessionService/MakeSetBusy")
    public void makeSetBusy(
        @WebParam(partName = "parameters", name = "MakeSetBusyRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalRequest parameters
    ) throws MakeSetBusyException, SessionNotCreatedException;

    @WebResult(name = "GetAgentAddressesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "response")
    @WebMethod(operationName = "GetAgentAddresses", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetAgentAddresses")
    public com.nortel.soa.oi.cct.types.sessionservice.AddressList getAgentAddresses(
        @WebParam(partName = "parameters", name = "GetAgentAddressesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.GetAgentAddressesRequest parameters
    ) throws GetAgentAddressesException, SessionNotCreatedException;

    @WebResult(name = "AddressResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "GetAddress", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetAddress")
    public com.nortel.soa.oi.cct.types.sessionservice.AddressResponse getAddress(
        @WebParam(partName = "parameters", name = "GetAddressRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.GetAddressRequest parameters
    ) throws GetAddressException, SessionNotCreatedException;

    @WebMethod(operationName = "GenerateDTMF", action = "http://www.nortel.com/soa/oi/cct/SessionService/GenerateDTMF")
    public void generateDTMF(
        @WebParam(partName = "parameters", name = "GenerateDTMFRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.GenerateDTMFRequest parameters
    ) throws GenerateDTMFException, SessionNotCreatedException;

    @WebMethod(operationName = "SetActivityCode", action = "http://www.nortel.com/soa/oi/cct/SessionService/SetActivityCode")
    public void setActivityCode(
        @WebParam(partName = "parameters", name = "SetActivityCodeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.SetActivityCodeRequest parameters
    ) throws SetActivityCodeException, SessionNotCreatedException;

    @WebMethod(operationName = "TransferContact", action = "http://www.nortel.com/soa/oi/cct/SessionService/TransferContact")
    public void transferContact(
        @WebParam(partName = "parameters", name = "TransferContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalContactAddressRequest parameters
    ) throws TransferContactException, SessionNotCreatedException;

    @WebMethod(operationName = "LoginAgentToTerminal", action = "http://www.nortel.com/soa/oi/cct/SessionService/LoginAgentToTerminal")
    public void loginAgentToTerminal(
        @WebParam(partName = "parameters", name = "LoginAgentToTerminalRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.LoginAgentToTerminalRequest parameters
    ) throws SessionNotCreatedException, LoginAgentToTerminalException;

    @WebResult(name = "GetAgentsResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "response")
    @WebMethod(operationName = "GetAgents", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetAgents")
    public com.nortel.soa.oi.cct.types.sessionservice.GetAgentsResponse getAgents(
        @WebParam(partName = "parameters", name = "GetAgentsRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.SsoRequest parameters
    ) throws GetAgentsException, SessionNotCreatedException;

    @WebResult(name = "GetCurrentAddressCountResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "response")
    @WebMethod(operationName = "GetCurrentAddressCount", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetCurrentAddressCouint")
    public int getCurrentAddressCount(
        @WebParam(partName = "parameters", name = "GetCurrentAddressCountRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.SsoRequest parameters
    ) throws GetCurrentAddressCountException, SessionNotCreatedException;

    @WebResult(name = "GetContactResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "response")
    @WebMethod(operationName = "GetContact", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetContact")
    public com.nortel.soa.oi.cct.types.sessionservice.ContactResponse getContact(
        @WebParam(partName = "parameters", name = "GetContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.ContactRequest parameters
    ) throws SessionNotCreatedException, GetContactException;

    @WebResult(name = "GetTerminalAddressesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "GetTerminalAddresses", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetTerminalAddresses")
    public com.nortel.soa.oi.cct.types.sessionservice.AddressList getTerminalAddresses(
        @WebParam(partName = "parameters", name = "GetTerminalAddressesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.GetTerminalAddressesRequest parameters
    ) throws GetTerminalAddressesException, SessionNotCreatedException;

    @WebResult(name = "LogInToCCTServerResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "LogInToCCTServer", action = "http://www.nortel.com/soa/oi/cct/SessionService/LogInToCCTServer")
    public com.nortel.soa.oi.cct.types.sessionservice.LogInToCCTServerResponse logInToCCTServer(
        @WebParam(partName = "parameters", name = "LogInToCCTServerRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.LogInToCCTServerRequest parameters
    ) throws LogInToCCTServerException;

    @WebMethod(operationName = "SetContactData", action = "http://www.nortel.com/soa/oi/cct/SessionService/SetContactData")
    public void setContactData(
        @WebParam(partName = "parameters", name = "SetContactDataRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.SetContactDataRequest parameters
    ) throws SessionNotCreatedException, SetContactDataException;

    @WebResult(name = "GetAddressesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "GetAddresses", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetAddresses")
    public com.nortel.soa.oi.cct.types.sessionservice.AddressList getAddresses(
        @WebParam(partName = "parameters", name = "GetAddressesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.GetAddressesRequest parameters
    ) throws SessionNotCreatedException, GetAddressesException;

    @WebMethod(operationName = "CompleteConference", action = "http://www.nortel.com/soa/oi/cct/SessionService/CompleteConference")
    public void completeConference(
        @WebParam(partName = "parameters", name = "CompleteConferenceRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalContactContactRequest parameters
    ) throws CompleteConferenceException, SessionNotCreatedException;

    @WebMethod(operationName = "SetToNotReadyState", action = "http://www.nortel.com/soa/oi/cct/SessionService/SetToNotReadyState")
    public void setToNotReadyState(
        @WebParam(partName = "parameters", name = "SetToNotReadyStatetRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalRequest parameters
    ) throws SessionNotCreatedException, SetToNotReadyStateException;

    @WebMethod(operationName = "SetToReadyState", action = "http://www.nortel.com/soa/oi/cct/SessionService/SetToReadyState")
    public void setToReadyState(
        @WebParam(partName = "parameters", name = "SetToReadyStatetRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalRequest parameters
    ) throws SetToReadyStateException, SessionNotCreatedException;

    @WebResult(name = "GetContactDataResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "parameters")
    @WebMethod(operationName = "GetContactData", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetContactData")
    public com.nortel.soa.oi.cct.types.sessionservice.GetContactDataResponse getContactData(
        @WebParam(partName = "parameters", name = "GetContactDataRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.ContactRequest parameters
    ) throws SessionNotCreatedException, GetContactDataException;

    @WebResult(name = "GetTerminalsResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "GetTerminals", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetTerminals")
    public com.nortel.soa.oi.cct.types.sessionservice.TerminalList getTerminals(
        @WebParam(partName = "parameters", name = "GetTerminalsRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.GetTerminalsRequest parameters
    ) throws GetTerminalsException, SessionNotCreatedException;

    @WebResult(name = "InitiateSupervisedTransferResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "InitiateSupervisedTransfer", action = "http://www.nortel.com/soa/oi/cct/SessionService/InitiateSupervisedTransfer")
    public com.nortel.soa.oi.cct.types.sessionservice.ContactResponse initiateSupervisedTransfer(
        @WebParam(partName = "parameters", name = "InitiateSupervisedTransferRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalContactAddressRequest parameters
    ) throws InitiateSupervisedTransferException, SessionNotCreatedException;

    @WebMethod(operationName = "LogoutAgent", action = "http://www.nortel.com/soa/oi/cct/SessionService/LogoutAgent")
    public void logoutAgent(
        @WebParam(partName = "parameters", name = "LogoutAgentRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.LogoutAgentRequest parameters
    ) throws SessionNotCreatedException, LogoutAgentException;

    @WebResult(name = "CreateContactResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "CreateContact", action = "http://www.nortel.com/soa/oi/cct/SessionService/CreateContact")
    public com.nortel.soa.oi.cct.types.sessionservice.ContactResponse createContact(
        @WebParam(partName = "parameters", name = "CreateContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.CreateContactRequest parameters
    ) throws SessionNotCreatedException, CreateContactException;

    @WebMethod(operationName = "EmergencyKey", action = "http://www.nortel.com/soa/oi/cct/SessionService/EmergencyKey")
    public void emergencyKey(
        @WebParam(partName = "parameters", name = "EmergencyKeyRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalContactRequest parameters
    ) throws EmergencyKeyException, SessionNotCreatedException;

    @WebMethod(operationName = "LogOffFromCCTServer", action = "http://www.nortel.com/soa/oi/cct/SessionService/LogOffFromCCTServer")
    public void logOffFromCCTServer(
        @WebParam(partName = "parameters", name = "LogOffFromCCTServerRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.LogOffFromCCTServerRequest parameters
    ) throws LogOffFromCCTServerException, SessionNotCreatedException;

    @WebResult(name = "GetIntrinsicsResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "response")
    @WebMethod(operationName = "GetIntrinsics", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetIntrinsics")
    public com.nortel.soa.oi.cct.types.sessionservice.GetIntrinsicsResponse getIntrinsics(
        @WebParam(partName = "parameters", name = "GetIntrinsicsRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.ContactRequest parameters
    ) throws GetIntrinsicsException, SessionNotCreatedException;

    @WebMethod(operationName = "HoldContact", action = "http://www.nortel.com/soa/oi/cct/SessionService/HoldContact")
    public void holdContact(
        @WebParam(partName = "parameters", name = "HoldContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.TerminalContactRequest parameters
    ) throws HoldContactException, SessionNotCreatedException;

    @WebResult(name = "TerminalResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "GetTerminal", action = "http://www.nortel.com/soa/oi/cct/SessionService/GetTerminal")
    public com.nortel.soa.oi.cct.types.sessionservice.TerminalResponse getTerminal(
        @WebParam(partName = "parameters", name = "GetTerminalRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService")
        com.nortel.soa.oi.cct.types.sessionservice.GetTerminalRequest parameters
    ) throws GetTerminalException, SessionNotCreatedException;
}
