
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.093+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetActivityCodeException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetActivityCodeException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setActivityCodeException;

    public SetActivityCodeException() {
        super();
    }
    
    public SetActivityCodeException(String message) {
        super(message);
    }
    
    public SetActivityCodeException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetActivityCodeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setActivityCodeException) {
        super(message);
        this.setActivityCodeException = setActivityCodeException;
    }

    public SetActivityCodeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setActivityCodeException, Throwable cause) {
        super(message, cause);
        this.setActivityCodeException = setActivityCodeException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setActivityCodeException;
    }
}
