
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetIntrinsicsException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetIntrinsicsException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setIntrinsicsException;

    public SetIntrinsicsException() {
        super();
    }
    
    public SetIntrinsicsException(String message) {
        super(message);
    }
    
    public SetIntrinsicsException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetIntrinsicsException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setIntrinsicsException) {
        super(message);
        this.setIntrinsicsException = setIntrinsicsException;
    }

    public SetIntrinsicsException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setIntrinsicsException, Throwable cause) {
        super(message, cause);
        this.setIntrinsicsException = setIntrinsicsException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setIntrinsicsException;
    }
}
