
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.171+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetToNotReadyStateException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetToNotReadyStateException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setToNotReadyStateException;

    public SetToNotReadyStateException() {
        super();
    }
    
    public SetToNotReadyStateException(String message) {
        super(message);
    }
    
    public SetToNotReadyStateException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetToNotReadyStateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setToNotReadyStateException) {
        super(message);
        this.setToNotReadyStateException = setToNotReadyStateException;
    }

    public SetToNotReadyStateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setToNotReadyStateException, Throwable cause) {
        super(message, cause);
        this.setToNotReadyStateException = setToNotReadyStateException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setToNotReadyStateException;
    }
}
