
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.171+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetToReadyStateException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetToReadyStateException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setToReadyStateException;

    public SetToReadyStateException() {
        super();
    }
    
    public SetToReadyStateException(String message) {
        super(message);
    }
    
    public SetToReadyStateException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetToReadyStateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setToReadyStateException) {
        super(message);
        this.setToReadyStateException = setToReadyStateException;
    }

    public SetToReadyStateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setToReadyStateException, Throwable cause) {
        super(message, cause);
        this.setToReadyStateException = setToReadyStateException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setToReadyStateException;
    }
}
