
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24.093+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "TransferContactException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class TransferContactException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo transferContactException;

    public TransferContactException() {
        super();
    }
    
    public TransferContactException(String message) {
        super(message);
    }
    
    public TransferContactException(String message, Throwable cause) {
        super(message, cause);
    }

    public TransferContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo transferContactException) {
        super(message);
        this.transferContactException = transferContactException;
    }

    public TransferContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo transferContactException, Throwable cause) {
        super(message, cause);
        this.transferContactException = transferContactException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.transferContactException;
    }
}
