
package com.nortel.soa.oi.cct.sessionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:24+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "UnHoldContactException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class UnHoldContactException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo unHoldContactException;

    public UnHoldContactException() {
        super();
    }
    
    public UnHoldContactException(String message) {
        super(message);
    }
    
    public UnHoldContactException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnHoldContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo unHoldContactException) {
        super(message);
        this.unHoldContactException = unHoldContactException;
    }

    public UnHoldContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo unHoldContactException, Throwable cause) {
        super(message, cause);
        this.unHoldContactException = unHoldContactException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.unHoldContactException;
    }
}
