package com.nortel.soa.oi.cct.notificationproducer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:03:09.359+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/NotificationProducer", name = "NotificationProducer")
@XmlSeeAlso({com.nortel.soa.oi.cct.types.notificationproducer.ObjectFactory.class, com.nortel.soa.oi.cct.notification.ObjectFactory.class, com.nortel.soa.oi.cct.notification.faults.ObjectFactory.class, com.nortel.soa.oi.cct.basenotification.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class})
public interface NotificationProducer {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetVersionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer", partName = "result")
    @WebMethod(operationName = "GetVersion", action = "http://www.nortel.com/soa/oi/cct/notificationproducer/service/GetVersion")
    public com.nortel.soa.oi.cct.types.GetVersionResponse getVersion(
        @WebParam(partName = "parameters", name = "GetVersionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        com.nortel.soa.oi.cct.types.GetVersionRequest parameters
    ) throws GetVersionFault;

    @RequestWrapper(localName = "Renew", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer", className = "com.nortel.soa.oi.cct.types.notificationproducer.Renew")
    @WebMethod(operationName = "Renew", action = "http://www.nortel.com/soa/oi/cct/notificationproducer/service/Renew")
    @ResponseWrapper(localName = "RenewResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer", className = "com.nortel.soa.oi.cct.types.notificationproducer.RenewResponse")
    public void renew(
        @WebParam(name = "SubscriptionReference", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        org.xmlsoap.schemas.ws._2003._03.addressing.EndpointReferenceType subscriptionReference,
        @WebParam(name = "ssoToken", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        com.nortel.soa.oi.cct.types.SsoToken ssoToken,
        @WebParam(mode = WebParam.Mode.INOUT, name = "TerminationTime", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> terminationTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "CurrentTime", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> currentTime
    ) throws ResourceUnknownFault, RenewSubscriptionFailedFault, UnacceptableTerminationTimeFault;

    @WebResult(name = "Success", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
    @RequestWrapper(localName = "Unsubscribe", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer", className = "com.nortel.soa.oi.cct.types.notificationproducer.Unsubscribe")
    @WebMethod(operationName = "Unsubscribe", action = "http://www.nortel.com/soa/oi/cct/notificationproducer/service/Unsubscribe")
    @ResponseWrapper(localName = "UnsubscribeResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer", className = "com.nortel.soa.oi.cct.types.notificationproducer.UnsubscribeResponse")
    public boolean unsubscribe(
        @WebParam(name = "SubscriptionReference", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        org.xmlsoap.schemas.ws._2003._03.addressing.EndpointReferenceType subscriptionReference,
        @WebParam(name = "ssoToken", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        com.nortel.soa.oi.cct.types.SsoToken ssoToken
    ) throws ResourceUnknownFault, UnableToDestroySubscriptionFault;

    @WebResult(name = "SubscriptionReference", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
    @RequestWrapper(localName = "Subscribe", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer", className = "com.nortel.soa.oi.cct.types.notificationproducer.Subscribe")
    @WebMethod(operationName = "Subscribe", action = "http://www.nortel.com/soa/oi/cct/notificationproducer/service/Subscribe")
    @ResponseWrapper(localName = "SubscribeResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer", className = "com.nortel.soa.oi.cct.types.notificationproducer.SubscribeResponse")
    public org.xmlsoap.schemas.ws._2003._03.addressing.EndpointReferenceType subscribe(
        @WebParam(name = "ConsumerReference", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        org.xmlsoap.schemas.ws._2003._03.addressing.EndpointReferenceType consumerReference,
        @WebParam(name = "TopicExpression", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        com.nortel.soa.oi.cct.basenotification.TopicExpressionType topicExpression,
        @WebParam(name = "UseNotify", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        java.lang.Boolean useNotify,
        @WebParam(name = "Precondition", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryExpressionType precondition,
        @WebParam(name = "Selector", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryExpressionType selector,
        @WebParam(name = "SubscriptionPolicy", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        com.nortel.soa.oi.cct.notification.SubscriptionPolicyType subscriptionPolicy,
        @WebParam(name = "InitialTerminationTime", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        javax.xml.datatype.XMLGregorianCalendar initialTerminationTime,
        @WebParam(name = "ssoToken", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationProducer")
        com.nortel.soa.oi.cct.types.SsoToken ssoToken
    ) throws ResourceUnknownFault, TopicPathDialectUnknownFault, SubscribeCreationFailedFault;
}
