
package com.nortel.soa.oi.cct.notificationproducer;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:03:09.296+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "RenewSubscriptionFailedFault", targetNamespace = "http://www.nortel.com/soa/oi/cct/notification/faults")
public class RenewSubscriptionFailedFault extends Exception {
    
    private com.nortel.soa.oi.cct.notification.RenewSubscriptionFailedFaultType renewSubscriptionFailedFault;

    public RenewSubscriptionFailedFault() {
        super();
    }
    
    public RenewSubscriptionFailedFault(String message) {
        super(message);
    }
    
    public RenewSubscriptionFailedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public RenewSubscriptionFailedFault(String message, com.nortel.soa.oi.cct.notification.RenewSubscriptionFailedFaultType renewSubscriptionFailedFault) {
        super(message);
        this.renewSubscriptionFailedFault = renewSubscriptionFailedFault;
    }

    public RenewSubscriptionFailedFault(String message, com.nortel.soa.oi.cct.notification.RenewSubscriptionFailedFaultType renewSubscriptionFailedFault, Throwable cause) {
        super(message, cause);
        this.renewSubscriptionFailedFault = renewSubscriptionFailedFault;
    }

    public com.nortel.soa.oi.cct.notification.RenewSubscriptionFailedFaultType getFaultInfo() {
        return this.renewSubscriptionFailedFault;
    }
}
