
package com.nortel.soa.oi.cct.notificationproducer;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:03:09.296+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "ResourceUnknownFault", targetNamespace = "http://www.nortel.com/soa/oi/cct/notification/faults")
public class ResourceUnknownFault extends Exception {
    
    private com.nortel.soa.oi.cct.notification.ResourceUnknownFaultType resourceUnknownFault;

    public ResourceUnknownFault() {
        super();
    }
    
    public ResourceUnknownFault(String message) {
        super(message);
    }
    
    public ResourceUnknownFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceUnknownFault(String message, com.nortel.soa.oi.cct.notification.ResourceUnknownFaultType resourceUnknownFault) {
        super(message);
        this.resourceUnknownFault = resourceUnknownFault;
    }

    public ResourceUnknownFault(String message, com.nortel.soa.oi.cct.notification.ResourceUnknownFaultType resourceUnknownFault, Throwable cause) {
        super(message, cause);
        this.resourceUnknownFault = resourceUnknownFault;
    }

    public com.nortel.soa.oi.cct.notification.ResourceUnknownFaultType getFaultInfo() {
        return this.resourceUnknownFault;
    }
}
