package com.nortel.soa.oi.cct.notificationproducer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:03:09.390+03:00
 * Generated source version: 2.6.1
 *
 */
@WebServiceClient(name = "SOAOICCT_NotificationProducer",
                  wsdlLocation = "http://ccc-aacc-mgt:9084/SOAOICCT/services/NotificationProducer?wsdl",
                  targetNamespace = "http://www.nortel.com/soa/oi/cct/NotificationProducer")
public class SOAOICCTNotificationProducer extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.nortel.com/soa/oi/cct/NotificationProducer", "SOAOICCT_NotificationProducer");
    public final static QName NotificationProducer = new QName("http://www.nortel.com/soa/oi/cct/NotificationProducer", "NotificationProducer");
    static {
        URL url = null;
        try {
            url = new URL("http://"+System.getProperty("cctServiceHostAndPort","ccc-aacc-mgt")+"/SOAOICCT/services/NotificationProducer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SOAOICCTNotificationProducer.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://ccc-aacc-mgt:9084/SOAOICCT/services/NotificationProducer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SOAOICCTNotificationProducer(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SOAOICCTNotificationProducer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAOICCTNotificationProducer() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAOICCTNotificationProducer(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAOICCTNotificationProducer(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAOICCTNotificationProducer(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NotificationProducer
     */
    @WebEndpoint(name = "NotificationProducer")
    public NotificationProducer getNotificationProducer() {
        return super.getPort(NotificationProducer, NotificationProducer.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationProducer
     */
    @WebEndpoint(name = "NotificationProducer")
    public NotificationProducer getNotificationProducer(WebServiceFeature... features) {
        return super.getPort(NotificationProducer, NotificationProducer.class, features);
    }

}
