
package com.nortel.soa.oi.cct.notificationproducer;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:03:09.343+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "TopicPathDialectUnknownFault", targetNamespace = "http://www.nortel.com/soa/oi/cct/notification/faults")
public class TopicPathDialectUnknownFault extends Exception {
    
    private com.nortel.soa.oi.cct.notification.TopicPathDialectUnknownFaultType topicPathDialectUnknownFault;

    public TopicPathDialectUnknownFault() {
        super();
    }
    
    public TopicPathDialectUnknownFault(String message) {
        super(message);
    }
    
    public TopicPathDialectUnknownFault(String message, Throwable cause) {
        super(message, cause);
    }

    public TopicPathDialectUnknownFault(String message, com.nortel.soa.oi.cct.notification.TopicPathDialectUnknownFaultType topicPathDialectUnknownFault) {
        super(message);
        this.topicPathDialectUnknownFault = topicPathDialectUnknownFault;
    }

    public TopicPathDialectUnknownFault(String message, com.nortel.soa.oi.cct.notification.TopicPathDialectUnknownFaultType topicPathDialectUnknownFault, Throwable cause) {
        super(message, cause);
        this.topicPathDialectUnknownFault = topicPathDialectUnknownFault;
    }

    public com.nortel.soa.oi.cct.notification.TopicPathDialectUnknownFaultType getFaultInfo() {
        return this.topicPathDialectUnknownFault;
    }
}
