
package com.nortel.soa.oi.cct.notificationproducer;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:03:09.328+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "UnableToDestroySubscriptionFault", targetNamespace = "http://www.nortel.com/soa/oi/cct/notification/faults")
public class UnableToDestroySubscriptionFault extends Exception {
    
    private com.nortel.soa.oi.cct.notification.UnableToDestroySubscriptionFaultType unableToDestroySubscriptionFault;

    public UnableToDestroySubscriptionFault() {
        super();
    }
    
    public UnableToDestroySubscriptionFault(String message) {
        super(message);
    }
    
    public UnableToDestroySubscriptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnableToDestroySubscriptionFault(String message, com.nortel.soa.oi.cct.notification.UnableToDestroySubscriptionFaultType unableToDestroySubscriptionFault) {
        super(message);
        this.unableToDestroySubscriptionFault = unableToDestroySubscriptionFault;
    }

    public UnableToDestroySubscriptionFault(String message, com.nortel.soa.oi.cct.notification.UnableToDestroySubscriptionFaultType unableToDestroySubscriptionFault, Throwable cause) {
        super(message, cause);
        this.unableToDestroySubscriptionFault = unableToDestroySubscriptionFault;
    }

    public com.nortel.soa.oi.cct.notification.UnableToDestroySubscriptionFaultType getFaultInfo() {
        return this.unableToDestroySubscriptionFault;
    }
}
