
package com.nortel.soa.oi.cct.notificationproducer;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:03:09.312+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "UnacceptableTerminationTimeFault", targetNamespace = "http://www.nortel.com/soa/oi/cct/notification/faults")
public class UnacceptableTerminationTimeFault extends Exception {
    
    private com.nortel.soa.oi.cct.notification.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault;

    public UnacceptableTerminationTimeFault() {
        super();
    }
    
    public UnacceptableTerminationTimeFault(String message) {
        super(message);
    }
    
    public UnacceptableTerminationTimeFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnacceptableTerminationTimeFault(String message, com.nortel.soa.oi.cct.notification.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault) {
        super(message);
        this.unacceptableTerminationTimeFault = unacceptableTerminationTimeFault;
    }

    public UnacceptableTerminationTimeFault(String message, com.nortel.soa.oi.cct.notification.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault, Throwable cause) {
        super(message, cause);
        this.unacceptableTerminationTimeFault = unacceptableTerminationTimeFault;
    }

    public com.nortel.soa.oi.cct.notification.UnacceptableTerminationTimeFaultType getFaultInfo() {
        return this.unacceptableTerminationTimeFault;
    }
}
