package com.nortel.soa.oi.cct.agentterminalservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:10.046+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/AgentTerminalService", name = "AgentTerminalService")
@XmlSeeAlso({com.nortel.soa.oi.cct.faults.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class, com.nortel.soa.oi.cct.types.agentterminalservice.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AgentTerminalService {

    @WebResult(name = "GetDoNotDisturbResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService", partName = "response")
    @WebMethod(operationName = "GetDoNotDisturb", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/GetDoNotDisturb")
    public com.nortel.soa.oi.cct.types.agentterminalservice.GetDoNotDisturbResponse getDoNotDisturb(
        @WebParam(partName = "parameters", name = "GetDoNotDisturbRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.TerminalRequest parameters
    ) throws SessionNotCreatedException, GetDoNotDisturbException;

    @WebMethod(operationName = "Login", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/Login")
    public void login(
        @WebParam(partName = "parameters", name = "LoginRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.AgentTerminalLoginRequest parameters
    ) throws SessionNotCreatedException, LoginException;

    @WebResult(name = "GetRelatedAddressesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService", partName = "response")
    @WebMethod(operationName = "GetRelatedAddresses", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/GetRelatedAddresses")
    public com.nortel.soa.oi.cct.types.agentterminalservice.GetRelatedAddressesResponse getRelatedAddresses(
        @WebParam(partName = "parameters", name = "GetRelatedAddressesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.TerminalRequest parameters
    ) throws SessionNotCreatedException, GetRelatedAddressesException;

    @WebMethod(operationName = "SetActivityCode", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/SetActivityCode")
    public void setActivityCode(
        @WebParam(partName = "parameters", name = "SetActivityCodeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.SetActivityCodeRequest parameters
    ) throws SessionNotCreatedException, SetActivityCodeException;

    @WebResult(name = "IsForwardedResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService", partName = "response")
    @WebMethod(operationName = "IsForwarded", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/IsForwarded")
    public com.nortel.soa.oi.cct.types.agentterminalservice.IsForwardedResponse isForwarded(
        @WebParam(partName = "parameters", name = "IsForwardedRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.TerminalRequest parameters
    ) throws SessionNotCreatedException, IsForwardedException;

    @WebResult(name = "GetTerminalConnectionsResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService", partName = "response")
    @WebMethod(operationName = "GetTerminalConnections", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/GetTerminalConnections")
    public com.nortel.soa.oi.cct.types.agentterminalservice.GetTerminalConnectionsResponse getTerminalConnections(
        @WebParam(partName = "parameters", name = "GetTerminalConnectionsRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.TerminalRequest parameters
    ) throws SessionNotCreatedException, GetTerminalConnectionsException;

    @WebMethod(operationName = "SetIsReady", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/SetIsReady")
    public void setIsReady(
        @WebParam(partName = "parameters", name = "SetIsReadyRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.BooleanTerminalRequest parameters
    ) throws SessionNotCreatedException, SetIsReadyException;

    @WebResult(name = "IsReadyResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService", partName = "response")
    @WebMethod(operationName = "IsReady", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/IsReady")
    public com.nortel.soa.oi.cct.types.agentterminalservice.IsReadyResponse isReady(
        @WebParam(partName = "parameters", name = "IsReadyRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.TerminalRequest parameters
    ) throws IsReadyException, SessionNotCreatedException;

    @WebMethod(operationName = "SetNotReadyReasonCode", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/SetNotReadyReasonCode")
    public void setNotReadyReasonCode(
        @WebParam(partName = "parameters", name = "SetNotReadyReasonCodeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.StringTerminalRequest parameters
    ) throws SessionNotCreatedException, SetNotReadyReasonCodeException;

    @WebResult(name = "GetLoginIdResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService", partName = "response")
    @WebMethod(operationName = "GetLoginId", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/GetLoginId")
    public com.nortel.soa.oi.cct.types.agentterminalservice.GetLoginIdResponse getLoginId(
        @WebParam(partName = "parameters", name = "GetLoginIdRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.TerminalRequest parameters
    ) throws GetLoginIdException, SessionNotCreatedException;

    @WebMethod(operationName = "Logout", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/Logout")
    public void logout(
        @WebParam(partName = "parameters", name = "LogoutRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.AgentTerminalLogoutRequest parameters
    ) throws SessionNotCreatedException, LogoutException;

    @WebResult(name = "GetCapabilitiesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService", partName = "response")
    @WebMethod(operationName = "GetCapabilities", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/GetCapabilities")
    public com.nortel.soa.oi.cct.types.agentterminalservice.GetAgentTerminalCapabilitiesResponse getCapabilities(
        @WebParam(partName = "parameters", name = "GetCapabilitiesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.TerminalRequest parameters
    ) throws SessionNotCreatedException, GetCapabilitiesException;

    @WebResult(name = "GetVersionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService", partName = "response")
    @WebMethod(operationName = "GetVersion", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/GetVersion")
    public com.nortel.soa.oi.cct.types.GetVersionResponse getVersion(
        @WebParam(partName = "parameters", name = "GetVersionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.GetVersionRequest parameters
    ) throws SessionNotCreatedException, GetVersionException;

    @WebResult(name = "GetNotReadyReasonCodeResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService", partName = "response")
    @WebMethod(operationName = "GetNotReadyReasonCode", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/GetNotReadyReasonCode")
    public com.nortel.soa.oi.cct.types.agentterminalservice.GetNotReadyReasonCodeResponse getNotReadyReasonCode(
        @WebParam(partName = "parameters", name = "GetNotReadyReasonCodeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.TerminalRequest parameters
    ) throws SessionNotCreatedException, GetNotReadyReasonCodeException;

    @WebResult(name = "GetActivityCodeResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService", partName = "response")
    @WebMethod(operationName = "GetActivityCode", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/GetActivityCode")
    public com.nortel.soa.oi.cct.types.agentterminalservice.GetActivityCodeResponse getActivityCode(
        @WebParam(partName = "parameters", name = "GetActivityCodeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.TerminalRequest parameters
    ) throws GetActivityCodeException, SessionNotCreatedException;

    @WebMethod(operationName = "CallSupervisor", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalService/CallSupervisor")
    public void callSupervisor(
        @WebParam(partName = "parameters", name = "CallSupervisorRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalService")
        com.nortel.soa.oi.cct.types.agentterminalservice.TerminalAddressRequest parameters
    ) throws SessionNotCreatedException, CallSupervisorException;
}
