
package com.nortel.soa.oi.cct.agentterminalservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:09.921+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "IsForwardedException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class IsForwardedException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo isForwardedException;

    public IsForwardedException() {
        super();
    }
    
    public IsForwardedException(String message) {
        super(message);
    }
    
    public IsForwardedException(String message, Throwable cause) {
        super(message, cause);
    }

    public IsForwardedException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo isForwardedException) {
        super(message);
        this.isForwardedException = isForwardedException;
    }

    public IsForwardedException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo isForwardedException, Throwable cause) {
        super(message, cause);
        this.isForwardedException = isForwardedException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.isForwardedException;
    }
}
