
package com.nortel.soa.oi.cct.agentterminalservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:09.953+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "IsReadyException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class IsReadyException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo isReadyException;

    public IsReadyException() {
        super();
    }
    
    public IsReadyException(String message) {
        super(message);
    }
    
    public IsReadyException(String message, Throwable cause) {
        super(message, cause);
    }

    public IsReadyException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo isReadyException) {
        super(message);
        this.isReadyException = isReadyException;
    }

    public IsReadyException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo isReadyException, Throwable cause) {
        super(message, cause);
        this.isReadyException = isReadyException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.isReadyException;
    }
}
