
package com.nortel.soa.oi.cct.agentterminalservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:09.953+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetIsReadyException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetIsReadyException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setIsReadyException;

    public SetIsReadyException() {
        super();
    }
    
    public SetIsReadyException(String message) {
        super(message);
    }
    
    public SetIsReadyException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetIsReadyException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setIsReadyException) {
        super(message);
        this.setIsReadyException = setIsReadyException;
    }

    public SetIsReadyException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setIsReadyException, Throwable cause) {
        super(message, cause);
        this.setIsReadyException = setIsReadyException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setIsReadyException;
    }
}
