
package com.nortel.soa.oi.cct.addressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:11.875+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "CancelForwardingException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class CancelForwardingException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo cancelForwardingException;

    public CancelForwardingException() {
        super();
    }
    
    public CancelForwardingException(String message) {
        super(message);
    }
    
    public CancelForwardingException(String message, Throwable cause) {
        super(message, cause);
    }

    public CancelForwardingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo cancelForwardingException) {
        super(message);
        this.cancelForwardingException = cancelForwardingException;
    }

    public CancelForwardingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo cancelForwardingException, Throwable cause) {
        super(message, cause);
        this.cancelForwardingException = cancelForwardingException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.cancelForwardingException;
    }
}
