
package com.nortel.soa.oi.cct.addressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:11.968+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetForwardingException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetForwardingException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getForwardingException;

    public GetForwardingException() {
        super();
    }
    
    public GetForwardingException(String message) {
        super(message);
    }
    
    public GetForwardingException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetForwardingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getForwardingException) {
        super(message);
        this.getForwardingException = getForwardingException;
    }

    public GetForwardingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getForwardingException, Throwable cause) {
        super(message, cause);
        this.getForwardingException = getForwardingException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getForwardingException;
    }
}
