
package com.nortel.soa.oi.cct.addressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:11.921+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetTerminalStatusException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetTerminalStatusException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalStatusException;

    public GetTerminalStatusException() {
        super();
    }
    
    public GetTerminalStatusException(String message) {
        super(message);
    }
    
    public GetTerminalStatusException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTerminalStatusException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalStatusException) {
        super(message);
        this.getTerminalStatusException = getTerminalStatusException;
    }

    public GetTerminalStatusException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalStatusException, Throwable cause) {
        super(message, cause);
        this.getTerminalStatusException = getTerminalStatusException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getTerminalStatusException;
    }
}
