
package com.nortel.soa.oi.cct.addressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:11.843+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "OriginateException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class OriginateException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo originateException;

    public OriginateException() {
        super();
    }
    
    public OriginateException(String message) {
        super(message);
    }
    
    public OriginateException(String message, Throwable cause) {
        super(message, cause);
    }

    public OriginateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo originateException) {
        super(message);
        this.originateException = originateException;
    }

    public OriginateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo originateException, Throwable cause) {
        super(message, cause);
        this.originateException = originateException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.originateException;
    }
}
