
package com.nortel.soa.oi.cct.addressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:11.937+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "PresenceSubscribeException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class PresenceSubscribeException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo presenceSubscribeException;

    public PresenceSubscribeException() {
        super();
    }
    
    public PresenceSubscribeException(String message) {
        super(message);
    }
    
    public PresenceSubscribeException(String message, Throwable cause) {
        super(message, cause);
    }

    public PresenceSubscribeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo presenceSubscribeException) {
        super(message);
        this.presenceSubscribeException = presenceSubscribeException;
    }

    public PresenceSubscribeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo presenceSubscribeException, Throwable cause) {
        super(message, cause);
        this.presenceSubscribeException = presenceSubscribeException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.presenceSubscribeException;
    }
}
