
package com.nortel.soa.oi.cct.addressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:11.953+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SendInstantMessageException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SendInstantMessageException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo sendInstantMessageException;

    public SendInstantMessageException() {
        super();
    }
    
    public SendInstantMessageException(String message) {
        super(message);
    }
    
    public SendInstantMessageException(String message, Throwable cause) {
        super(message, cause);
    }

    public SendInstantMessageException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo sendInstantMessageException) {
        super(message);
        this.sendInstantMessageException = sendInstantMessageException;
    }

    public SendInstantMessageException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo sendInstantMessageException, Throwable cause) {
        super(message, cause);
        this.sendInstantMessageException = sendInstantMessageException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.sendInstantMessageException;
    }
}
