
package com.nortel.soa.oi.cct.addressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:11.843+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetDoNotDisturbException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetDoNotDisturbException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setDoNotDisturbException;

    public SetDoNotDisturbException() {
        super();
    }
    
    public SetDoNotDisturbException(String message) {
        super(message);
    }
    
    public SetDoNotDisturbException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetDoNotDisturbException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setDoNotDisturbException) {
        super(message);
        this.setDoNotDisturbException = setDoNotDisturbException;
    }

    public SetDoNotDisturbException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setDoNotDisturbException, Throwable cause) {
        super(message, cause);
        this.setDoNotDisturbException = setDoNotDisturbException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setDoNotDisturbException;
    }
}
