
package com.nortel.soa.oi.cct.addressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:11.875+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetForwardingException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetForwardingException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setForwardingException;

    public SetForwardingException() {
        super();
    }
    
    public SetForwardingException(String message) {
        super(message);
    }
    
    public SetForwardingException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetForwardingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setForwardingException) {
        super(message);
        this.setForwardingException = setForwardingException;
    }

    public SetForwardingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setForwardingException, Throwable cause) {
        super(message, cause);
        this.setForwardingException = setForwardingException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setForwardingException;
    }
}
