
package com.nortel.soa.oi.cct.addressservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:11.984+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetMessageWaitingException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetMessageWaitingException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setMessageWaitingException;

    public SetMessageWaitingException() {
        super();
    }
    
    public SetMessageWaitingException(String message) {
        super(message);
    }
    
    public SetMessageWaitingException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetMessageWaitingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setMessageWaitingException) {
        super(message);
        this.setMessageWaitingException = setMessageWaitingException;
    }

    public SetMessageWaitingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setMessageWaitingException, Throwable cause) {
        super(message, cause);
        this.setMessageWaitingException = setMessageWaitingException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setMessageWaitingException;
    }
}
