package com.nortel.soa.oi.cct.agentterminalconnectionservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:39.390+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService", name = "AgentTerminalConnectionService")
@XmlSeeAlso({com.nortel.soa.oi.cct.types.agentterminalconnectionservice.ObjectFactory.class, com.nortel.soa.oi.cct.faults.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AgentTerminalConnectionService {

    @WebResult(name = "GetTransferConsultContactResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetTransferConsultContact", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/GetTransferConsultContact")
    public com.nortel.soa.oi.cct.types.agentterminalconnectionservice.ContactResponse getTransferConsultContact(
        @WebParam(partName = "parameters", name = "GetTransferConsultContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalConnectionRequest parameters
    ) throws SessionNotCreatedException, GetTransferConsultContactException;

    @WebResult(name = "GetTerminalResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetTerminal", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/GetTerminal")
    public com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalResponse getTerminal(
        @WebParam(partName = "parameters", name = "GetTerminalRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalConnectionRequest parameters
    ) throws SessionNotCreatedException, GetTerminalException;

    @WebResult(name = "GetConferenceConsultContactResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetConferenceConsultContact", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/GetConferenceConsultContact")
    public com.nortel.soa.oi.cct.types.agentterminalconnectionservice.ContactResponse getConferenceConsultContact(
        @WebParam(partName = "parameters", name = "GetConferenceConsultContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalConnectionRequest parameters
    ) throws SessionNotCreatedException, GetConferenceConsultContactException;

    @WebResult(name = "GetVersionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetVersion", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/GetVersion")
    public com.nortel.soa.oi.cct.types.GetVersionResponse getVersion(
        @WebParam(partName = "parameters", name = "GetVersionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.GetVersionRequest parameters
    ) throws SessionNotCreatedException, GetVersionException;

    @WebResult(name = "GetActivityCodeResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetActivityCode", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/GetActivityCode")
    public com.nortel.soa.oi.cct.types.agentterminalconnectionservice.GetActivityCodeResponse getActivityCode(
        @WebParam(partName = "parameters", name = "GetActivityCodeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalConnectionRequest parameters
    ) throws SessionNotCreatedException, GetActivityCodeException;

    @WebResult(name = "GetConnectionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetConnection", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/GetConnection")
    public com.nortel.soa.oi.cct.types.agentterminalconnectionservice.ConnectionResponse getConnection(
        @WebParam(partName = "parameters", name = "GetConnectionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalConnectionRequest parameters
    ) throws SessionNotCreatedException, GetConnectionException;

    @WebMethod(operationName = "EmergencyKey", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/EmergencyKey")
    public void emergencyKey(
        @WebParam(partName = "parameters", name = "EmergencyKeyRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalContactRequest parameters
    ) throws SessionNotCreatedException, EmergencyKeyException;

    @WebResult(name = "GetConsultContactResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetConsultContact", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/GetConsultContact")
    public com.nortel.soa.oi.cct.types.agentterminalconnectionservice.ContactResponse getConsultContact(
        @WebParam(partName = "parameters", name = "GetConsultContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalConnectionRequest parameters
    ) throws SessionNotCreatedException, GetConsultContactException;

    @WebResult(name = "GetContactResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetContact", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/GetContact")
    public com.nortel.soa.oi.cct.types.agentterminalconnectionservice.ContactResponse getContact(
        @WebParam(partName = "parameters", name = "GetContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalConnectionRequest parameters
    ) throws SessionNotCreatedException, GetContactException;

    @WebResult(name = "GetTerminalConnectionCapabilitiesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetTerminalConnectionCapabilities", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/GetTerminalConnectionCapabilities")
    public com.nortel.soa.oi.cct.types.agentterminalconnectionservice.GetAgentTerminalConnectionCapabilitiesResponse getTerminalConnectionCapabilities(
        @WebParam(partName = "parameters", name = "GetTerminalConnectionCapabilitiesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetTerminalConnectionCapabilitiesException, SessionNotCreatedException;

    @WebMethod(operationName = "SetActivityCode", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/SetActivityCode")
    public void setActivityCode(
        @WebParam(partName = "parameters", name = "SetActivityCodeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.SetActivityCodeRequest parameters
    ) throws SessionNotCreatedException, SetActivityCodeException;

    @WebResult(name = "GetStateResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetState", action = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService/GetState")
    public com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalConnectionStateResponse getState(
        @WebParam(partName = "parameters", name = "GetStateRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService")
        com.nortel.soa.oi.cct.types.agentterminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetStateException, SessionNotCreatedException;
}
