
package com.nortel.soa.oi.cct.agentterminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:39.281+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "EmergencyKeyException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class EmergencyKeyException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo emergencyKeyException;

    public EmergencyKeyException() {
        super();
    }
    
    public EmergencyKeyException(String message) {
        super(message);
    }
    
    public EmergencyKeyException(String message, Throwable cause) {
        super(message, cause);
    }

    public EmergencyKeyException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo emergencyKeyException) {
        super(message);
        this.emergencyKeyException = emergencyKeyException;
    }

    public EmergencyKeyException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo emergencyKeyException, Throwable cause) {
        super(message, cause);
        this.emergencyKeyException = emergencyKeyException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.emergencyKeyException;
    }
}
