
package com.nortel.soa.oi.cct.agentterminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:39.265+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetActivityCodeException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetActivityCodeException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getActivityCodeException;

    public GetActivityCodeException() {
        super();
    }
    
    public GetActivityCodeException(String message) {
        super(message);
    }
    
    public GetActivityCodeException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetActivityCodeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getActivityCodeException) {
        super(message);
        this.getActivityCodeException = getActivityCodeException;
    }

    public GetActivityCodeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getActivityCodeException, Throwable cause) {
        super(message, cause);
        this.getActivityCodeException = getActivityCodeException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getActivityCodeException;
    }
}
