
package com.nortel.soa.oi.cct.agentterminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:39.281+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetConsultContactException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetConsultContactException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getConsultContactException;

    public GetConsultContactException() {
        super();
    }
    
    public GetConsultContactException(String message) {
        super(message);
    }
    
    public GetConsultContactException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetConsultContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getConsultContactException) {
        super(message);
        this.getConsultContactException = getConsultContactException;
    }

    public GetConsultContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getConsultContactException, Throwable cause) {
        super(message, cause);
        this.getConsultContactException = getConsultContactException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getConsultContactException;
    }
}
