package com.nortel.soa.oi.cct.agentterminalconnectionservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:39.421+03:00
 * Generated source version: 2.6.1
 *
 */
@WebServiceClient(name = "SOAOICCT_AgentTerminalConnectionService",
                  wsdlLocation = "http://ccc-aacc-mgt:9084/SOAOICCT/services/AgentTerminalConnectionService?wsdl",
                  targetNamespace = "http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService")
public class SOAOICCTAgentTerminalConnectionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService", "SOAOICCT_AgentTerminalConnectionService");
    public final static QName AgentTerminalConnectionService = new QName("http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService", "AgentTerminalConnectionService");
    static {
        URL url = null;
        try {
            url = new URL("http://"+System.getProperty("cctServiceHostAndPort","ccc-aacc-mgt")+"/SOAOICCT/services/AgentTerminalConnectionService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SOAOICCTAgentTerminalConnectionService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://ccc-aacc-mgt:9084/SOAOICCT/services/AgentTerminalConnectionService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SOAOICCTAgentTerminalConnectionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SOAOICCTAgentTerminalConnectionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAOICCTAgentTerminalConnectionService() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAOICCTAgentTerminalConnectionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAOICCTAgentTerminalConnectionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAOICCTAgentTerminalConnectionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AgentTerminalConnectionService
     */
    @WebEndpoint(name = "AgentTerminalConnectionService")
    public AgentTerminalConnectionService getAgentTerminalConnectionService() {
        return super.getPort(AgentTerminalConnectionService, AgentTerminalConnectionService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgentTerminalConnectionService
     */
    @WebEndpoint(name = "AgentTerminalConnectionService")
    public AgentTerminalConnectionService getAgentTerminalConnectionService(WebServiceFeature... features) {
        return super.getPort(AgentTerminalConnectionService, AgentTerminalConnectionService.class, features);
    }

}
