
package com.nortel.soa.oi.cct.connectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:30.281+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "AlertException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class AlertException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo alertException;

    public AlertException() {
        super();
    }
    
    public AlertException(String message) {
        super(message);
    }
    
    public AlertException(String message, Throwable cause) {
        super(message, cause);
    }

    public AlertException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo alertException) {
        super(message);
        this.alertException = alertException;
    }

    public AlertException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo alertException, Throwable cause) {
        super(message, cause);
        this.alertException = alertException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.alertException;
    }
}
