
package com.nortel.soa.oi.cct.connectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:30.359+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetAddressException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetAddressException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAddressException;

    public GetAddressException() {
        super();
    }
    
    public GetAddressException(String message) {
        super(message);
    }
    
    public GetAddressException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAddressException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAddressException) {
        super(message);
        this.getAddressException = getAddressException;
    }

    public GetAddressException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAddressException, Throwable cause) {
        super(message, cause);
        this.getAddressException = getAddressException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getAddressException;
    }
}
