
package com.nortel.soa.oi.cct.connectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:30.296+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetConnectionCapabilitiesException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetConnectionCapabilitiesException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getConnectionCapabilitiesException;

    public GetConnectionCapabilitiesException() {
        super();
    }
    
    public GetConnectionCapabilitiesException(String message) {
        super(message);
    }
    
    public GetConnectionCapabilitiesException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetConnectionCapabilitiesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getConnectionCapabilitiesException) {
        super(message);
        this.getConnectionCapabilitiesException = getConnectionCapabilitiesException;
    }

    public GetConnectionCapabilitiesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getConnectionCapabilitiesException, Throwable cause) {
        super(message, cause);
        this.getConnectionCapabilitiesException = getConnectionCapabilitiesException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getConnectionCapabilitiesException;
    }
}
