
package com.nortel.soa.oi.cct.connectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:30.312+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetContactException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetContactException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactException;

    public GetContactException() {
        super();
    }
    
    public GetContactException(String message) {
        super(message);
    }
    
    public GetContactException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactException) {
        super(message);
        this.getContactException = getContactException;
    }

    public GetContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactException, Throwable cause) {
        super(message, cause);
        this.getContactException = getContactException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getContactException;
    }
}
