
package com.nortel.soa.oi.cct.connectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:30.343+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetRecordingStateException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetRecordingStateException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getRecordingStateException;

    public GetRecordingStateException() {
        super();
    }
    
    public GetRecordingStateException(String message) {
        super(message);
    }
    
    public GetRecordingStateException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetRecordingStateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getRecordingStateException) {
        super(message);
        this.getRecordingStateException = getRecordingStateException;
    }

    public GetRecordingStateException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getRecordingStateException, Throwable cause) {
        super(message, cause);
        this.getRecordingStateException = getRecordingStateException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getRecordingStateException;
    }
}
