
package com.nortel.soa.oi.cct.connectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:30.312+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetRecordingStateReasonException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetRecordingStateReasonException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getRecordingStateReasonException;

    public GetRecordingStateReasonException() {
        super();
    }
    
    public GetRecordingStateReasonException(String message) {
        super(message);
    }
    
    public GetRecordingStateReasonException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetRecordingStateReasonException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getRecordingStateReasonException) {
        super(message);
        this.getRecordingStateReasonException = getRecordingStateReasonException;
    }

    public GetRecordingStateReasonException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getRecordingStateReasonException, Throwable cause) {
        super(message, cause);
        this.getRecordingStateReasonException = getRecordingStateReasonException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getRecordingStateReasonException;
    }
}
