
package com.nortel.soa.oi.cct.connectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:30.156+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "ParkException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class ParkException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo parkException;

    public ParkException() {
        super();
    }
    
    public ParkException(String message) {
        super(message);
    }
    
    public ParkException(String message, Throwable cause) {
        super(message, cause);
    }

    public ParkException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo parkException) {
        super(message);
        this.parkException = parkException;
    }

    public ParkException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo parkException, Throwable cause) {
        super(message, cause);
        this.parkException = parkException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.parkException;
    }
}
