
package com.nortel.soa.oi.cct.connectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:30.375+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "RedirectException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class RedirectException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo redirectException;

    public RedirectException() {
        super();
    }
    
    public RedirectException(String message) {
        super(message);
    }
    
    public RedirectException(String message, Throwable cause) {
        super(message, cause);
    }

    public RedirectException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo redirectException) {
        super(message);
        this.redirectException = redirectException;
    }

    public RedirectException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo redirectException, Throwable cause) {
        super(message, cause);
        this.redirectException = redirectException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.redirectException;
    }
}
