
package com.nortel.soa.oi.cct.connectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:30.375+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "StartRecordingException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class StartRecordingException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo startRecordingException;

    public StartRecordingException() {
        super();
    }
    
    public StartRecordingException(String message) {
        super(message);
    }
    
    public StartRecordingException(String message, Throwable cause) {
        super(message, cause);
    }

    public StartRecordingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo startRecordingException) {
        super(message);
        this.startRecordingException = startRecordingException;
    }

    public StartRecordingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo startRecordingException, Throwable cause) {
        super(message, cause);
        this.startRecordingException = startRecordingException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.startRecordingException;
    }
}
