
package com.nortel.soa.oi.cct.connectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:30.281+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "StopRecordingException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class StopRecordingException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo stopRecordingException;

    public StopRecordingException() {
        super();
    }
    
    public StopRecordingException(String message) {
        super(message);
    }
    
    public StopRecordingException(String message, Throwable cause) {
        super(message, cause);
    }

    public StopRecordingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo stopRecordingException) {
        super(message);
        this.stopRecordingException = stopRecordingException;
    }

    public StopRecordingException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo stopRecordingException, Throwable cause) {
        super(message, cause);
        this.stopRecordingException = stopRecordingException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.stopRecordingException;
    }
}
