
package com.nortel.soa.oi.cct.userservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:05:01.734+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetTerminalsException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetTerminalsException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalsException;

    public GetTerminalsException() {
        super();
    }
    
    public GetTerminalsException(String message) {
        super(message);
    }
    
    public GetTerminalsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTerminalsException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalsException) {
        super(message);
        this.getTerminalsException = getTerminalsException;
    }

    public GetTerminalsException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalsException, Throwable cause) {
        super(message, cause);
        this.getTerminalsException = getTerminalsException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getTerminalsException;
    }
}
