
package com.nortel.soa.oi.cct.userservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:05:01.734+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "LogOffFromCCTServerException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class LogOffFromCCTServerException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo logOffFromCCTServerException;

    public LogOffFromCCTServerException() {
        super();
    }
    
    public LogOffFromCCTServerException(String message) {
        super(message);
    }
    
    public LogOffFromCCTServerException(String message, Throwable cause) {
        super(message, cause);
    }

    public LogOffFromCCTServerException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo logOffFromCCTServerException) {
        super(message);
        this.logOffFromCCTServerException = logOffFromCCTServerException;
    }

    public LogOffFromCCTServerException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo logOffFromCCTServerException, Throwable cause) {
        super(message, cause);
        this.logOffFromCCTServerException = logOffFromCCTServerException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.logOffFromCCTServerException;
    }
}
