
package com.nortel.soa.oi.cct.userservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:05:01.750+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SubscribeFailedFault", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService")
public class SubscribeFailedFault extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo subscribeFailedFault;

    public SubscribeFailedFault() {
        super();
    }
    
    public SubscribeFailedFault(String message) {
        super(message);
    }
    
    public SubscribeFailedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SubscribeFailedFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo subscribeFailedFault) {
        super(message);
        this.subscribeFailedFault = subscribeFailedFault;
    }

    public SubscribeFailedFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo subscribeFailedFault, Throwable cause) {
        super(message, cause);
        this.subscribeFailedFault = subscribeFailedFault;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.subscribeFailedFault;
    }
}
