
package com.nortel.soa.oi.cct.userservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:05:01.703+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "UnsubscribeFailedFault", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService")
public class UnsubscribeFailedFault extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo unsubscribeFailedFault;

    public UnsubscribeFailedFault() {
        super();
    }
    
    public UnsubscribeFailedFault(String message) {
        super(message);
    }
    
    public UnsubscribeFailedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnsubscribeFailedFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo unsubscribeFailedFault) {
        super(message);
        this.unsubscribeFailedFault = unsubscribeFailedFault;
    }

    public UnsubscribeFailedFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo unsubscribeFailedFault, Throwable cause) {
        super(message, cause);
        this.unsubscribeFailedFault = unsubscribeFailedFault;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.unsubscribeFailedFault;
    }
}
