package com.nortel.soa.oi.cct.userservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1 2014-01-31T11:05:01.781+03:00
 * Generated source version: 2.6.1
 *
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/UserService", name = "UserService")
@XmlSeeAlso({com.nortel.soa.oi.cct.notification.ObjectFactory.class, com.nortel.soa.oi.cct.types.sessionservice.ObjectFactory.class, com.nortel.soa.oi.cct.types.userservice.ObjectFactory.class, com.nortel.soa.oi.cct.faults.ObjectFactory.class, com.nortel.soa.oi.cct.basenotification.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class})
public interface UserService {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "LogInToCCTServerResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "LogInToCCTServer", action = "http://www.nortel.com/soa/oi/cct/UserService/LogInToCCTServer")
    public com.nortel.soa.oi.cct.types.sessionservice.LogInToCCTServerResponse logInToCCTServer(
            @WebParam(partName = "parameters", name = "LogInToCCTServerRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService") com.nortel.soa.oi.cct.types.sessionservice.LogInToCCTServerRequest parameters) throws LogInToCCTServerException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetVersionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "response")
    @WebMethod(operationName = "GetVersion", action = "http://www.nortel.com/soa/oi/cct/UserService/GetVersion")
    public com.nortel.soa.oi.cct.types.GetVersionResponse getVersion(
            @WebParam(partName = "parameters", name = "GetVersionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService") com.nortel.soa.oi.cct.types.GetVersionRequest parameters) throws SessionNotCreatedException, GetVersionException;

    @WebResult(name = "Success", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService")
    @RequestWrapper(localName = "Unsubscribe", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService", className = "com.nortel.soa.oi.cct.types.userservice.UnsubscribeType")
    @WebMethod(operationName = "Unsubscribe", action = "http://www.nortel.com/soa/oi/cct/UserService/Unsubscribe")
    @ResponseWrapper(localName = "UnsubscribeResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService", className = "com.nortel.soa.oi.cct.types.userservice.UnsubscribeResponseType")
    public boolean unsubscribe(
            @WebParam(name = "SubscriptionRef", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService") java.lang.String subscriptionRef,
            @WebParam(name = "ssoToken", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService") com.nortel.soa.oi.cct.types.SsoToken ssoToken) throws SessionNotCreatedException, UnsubscribeFailedFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TerminalResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "GetTerminal", action = "http://www.nortel.com/soa/oi/cct/UserService/GetTerminal")
    public com.nortel.soa.oi.cct.types.sessionservice.TerminalResponse getTerminal(
            @WebParam(partName = "parameters", name = "GetTerminalRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService") com.nortel.soa.oi.cct.types.sessionservice.GetTerminalRequest parameters) throws SessionNotCreatedException, GetTerminalException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebMethod(operationName = "LogOffFromCCTServer", action = "http://www.nortel.com/soa/oi/cct/UserService/LogOffFromCCTServer")
    public void logOffFromCCTServer(
            @WebParam(partName = "parameters", name = "LogOffFromCCTServerRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService") com.nortel.soa.oi.cct.types.sessionservice.LogOffFromCCTServerRequest parameters) throws SessionNotCreatedException, LogOffFromCCTServerException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetTerminalsResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "GetTerminals", action = "http://www.nortel.com/soa/oi/cct/UserService/GetTerminals")
    public com.nortel.soa.oi.cct.types.sessionservice.TerminalList getTerminals(
            @WebParam(partName = "parameters", name = "GetTerminalsRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService") com.nortel.soa.oi.cct.types.sessionservice.GetTerminalsRequest parameters) throws SessionNotCreatedException, GetTerminalsException;

    @WebResult(name = "SubscriptionRef", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService")
    @RequestWrapper(localName = "Subscribe", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService", className = "com.nortel.soa.oi.cct.types.userservice.SubscribeType")
    @WebMethod(operationName = "Subscribe", action = "http://www.nortel.com/soa/oi/cct/UserService/Subscribe")
    @ResponseWrapper(localName = "SubscribeResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService", className = "com.nortel.soa.oi.cct.types.userservice.SubscribeResponseType")
    public java.lang.String subscribe(
            @WebParam(name = "ConsumerEndpoint", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService") java.lang.String consumerEndpoint,
            @WebParam(name = "ssoToken", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/UserService") com.nortel.soa.oi.cct.types.SsoToken ssoToken) throws SessionNotCreatedException, SubscribeFailedFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetAgentsResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "response")
    @WebMethod(operationName = "GetAgents", action = "http://www.nortel.com/soa/oi/cct/UserService/GetAgents")
    public com.nortel.soa.oi.cct.types.sessionservice.GetAgentsResponse getAgents(
            @WebParam(partName = "parameters", name = "GetAgentsRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService") com.nortel.soa.oi.cct.types.sessionservice.SsoRequest parameters) throws GetAgentsException, SessionNotCreatedException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetAddressesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "GetAddresses", action = "http://www.nortel.com/soa/oi/cct/UserService/GetAddresses")
    public com.nortel.soa.oi.cct.types.sessionservice.AddressList getAddresses(
            @WebParam(partName = "parameters", name = "GetAddressesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService") com.nortel.soa.oi.cct.types.sessionservice.GetAddressesRequest parameters) throws SessionNotCreatedException, GetAddressesException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "AddressResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService", partName = "result")
    @WebMethod(operationName = "GetAddress", action = "http://www.nortel.com/soa/oi/cct/UserService/GetAddress")
    public com.nortel.soa.oi.cct.types.sessionservice.AddressResponse getAddress(
            @WebParam(partName = "parameters", name = "GetAddressRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/SessionService") com.nortel.soa.oi.cct.types.sessionservice.GetAddressRequest parameters) throws SessionNotCreatedException, GetAddressException;
}
