package com.nortel.soa.oi.cct.agentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:25.734+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/AgentService", name = "AgentService")
@XmlSeeAlso({com.nortel.soa.oi.cct.types.agentservice.ObjectFactory.class, com.nortel.soa.oi.cct.faults.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AgentService {

    @WebResult(name = "GetSupervisorResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "GetSupervisor", action = "http://www.nortel.com/soa/oi/cct/AgentService/GetSupervisor")
    public com.nortel.soa.oi.cct.types.agentservice.GetSupervisorResponse getSupervisor(
        @WebParam(partName = "parameters", name = "GetSupervisorRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws GetSupervisorException, SessionNotCreatedException;

    @WebResult(name = "GetTypeResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "GetType", action = "http://www.nortel.com/soa/oi/cct/AgentService/GetCapabilities")
    public com.nortel.soa.oi.cct.types.agentservice.StringResponse getType(
        @WebParam(partName = "parameters", name = "GetTypeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws GetTypeException, SessionNotCreatedException;

    @WebResult(name = "IsReadyResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "IsReady", action = "http://www.nortel.com/soa/oi/cct/AgentService/IsReady")
    public com.nortel.soa.oi.cct.types.agentservice.BooleanResponse isReady(
        @WebParam(partName = "parameters", name = "IsReadyRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws IsReadyException, SessionNotCreatedException;

    @WebResult(name = "GetNotReadyReasonCodeResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "GetNotReadyReasonCode", action = "http://www.nortel.com/soa/oi/cct/AgentService/GetNotReadyReasonCode")
    public com.nortel.soa.oi.cct.types.agentservice.StringResponse getNotReadyReasonCode(
        @WebParam(partName = "parameters", name = "GetNotReadyReasonCodeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws GetNotReadyReasonCodeException, SessionNotCreatedException;

    @WebMethod(operationName = "SetReady", action = "http://www.nortel.com/soa/oi/cct/AgentService/SetReady")
    public void setReady(
        @WebParam(partName = "parameters", name = "SetReadyRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.SetReadyRequest parameters
    ) throws SetReadyException, SessionNotCreatedException;

    @WebResult(name = "GetStaticVoiceTerminalResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "GetStaticVoiceTerminal", action = "http://www.nortel.com/soa/oi/cct/AgentService/GetStaticVoiceTerminal")
    public com.nortel.soa.oi.cct.types.agentservice.GetStaticVoiceTerminalResponse getStaticVoiceTerminal(
        @WebParam(partName = "parameters", name = "GetStaticVoiceTerminalRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws GetStaticVoiceTerminalException, SessionNotCreatedException;

    @WebResult(name = "GetCapabilitiesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "GetCapabilities", action = "http://www.nortel.com/soa/oi/cct/AgentService/GetCapabilities")
    public com.nortel.soa.oi.cct.types.agentservice.GetCapabilitiesResponse getCapabilities(
        @WebParam(partName = "parameters", name = "GetCapabilitiesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws GetCapabilitiesException, SessionNotCreatedException;

    @WebMethod(operationName = "SetStaticVoiceTerminal", action = "http://www.nortel.com/soa/oi/cct/AgentService/SetStaticVoiceTerminal")
    public void setStaticVoiceTerminal(
        @WebParam(partName = "parameters", name = "SetStaticVoiceTerminalRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.SetStaticVoiceTerminalRequest parameters
    ) throws SetStaticVoiceTerminalException, SessionNotCreatedException;

    @WebResult(name = "RetrieveResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "Retrieve", action = "http://www.nortel.com/soa/oi/cct/AgentService/Retrieve")
    public com.nortel.soa.oi.cct.types.agentservice.RetrieveResponse retrieve(
        @WebParam(partName = "parameters", name = "RetrieveRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.RetrieveRequest parameters
    ) throws RetrieveException, SessionNotCreatedException;

    @WebResult(name = "GetContactTypesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "GetContactTypes", action = "http://www.nortel.com/soa/oi/cct/AgentService/GetContactTypes")
    public com.nortel.soa.oi.cct.types.agentservice.GetAgentContactTypesResponse getContactTypes(
        @WebParam(partName = "parameters", name = "GetContactTypesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws GetContactTypesException, SessionNotCreatedException;

    @WebResult(name = "GetAgentsResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "GetAgents", action = "http://www.nortel.com/soa/oi/cct/AgentService/GetAgents")
    public com.nortel.soa.oi.cct.types.agentservice.GetAgentsResponse getAgents(
        @WebParam(partName = "parameters", name = "GetAgentsRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws GetAgentsException, SessionNotCreatedException;

    @WebMethod(operationName = "SetSupervisor", action = "http://www.nortel.com/soa/oi/cct/AgentService/SetSupervisor")
    public void setSupervisor(
        @WebParam(partName = "parameters", name = "SetSupervisorRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.SetSupervisorRequest parameters
    ) throws SetSupervisorException, SessionNotCreatedException;

    @WebMethod(operationName = "SetNotReadyReasonCode", action = "http://www.nortel.com/soa/oi/cct/AgentService/SetNotReadyReasonCode")
    public void setNotReadyReasonCode(
        @WebParam(partName = "parameters", name = "SetNotReadyReasonCodeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.SetNotReadyReasonCodeRequest parameters
    ) throws SetNotReadyReasonCodeException, SessionNotCreatedException;

    @WebMethod(operationName = "Login", action = "http://www.nortel.com/soa/oi/cct/AgentService/Login")
    public void login(
        @WebParam(partName = "parameters", name = "LoginRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.LoginRequest parameters
    ) throws LoginException, SessionNotCreatedException;

    @WebResult(name = "GetVersionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "GetVersion", action = "http://www.nortel.com/soa/oi/cct/AgentService/GetVersion")
    public com.nortel.soa.oi.cct.types.GetVersionResponse getVersion(
        @WebParam(partName = "parameters", name = "GetVersionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.GetVersionRequest parameters
    ) throws GetVersionException, SessionNotCreatedException;

    @WebMethod(operationName = "Logout", action = "http://www.nortel.com/soa/oi/cct/AgentService/Logout")
    public void logout(
        @WebParam(partName = "parameters", name = "LogoutRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws LogoutException, SessionNotCreatedException;

    @WebResult(name = "IsLoggedInResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "IsLoggedIn", action = "http://www.nortel.com/soa/oi/cct/AgentService/IsLoggedIn")
    public com.nortel.soa.oi.cct.types.agentservice.BooleanResponse isLoggedIn(
        @WebParam(partName = "parameters", name = "IsLoggedInRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws IsLoggedInException, SessionNotCreatedException;

    @WebResult(name = "IsSupervisorResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService", partName = "response")
    @WebMethod(operationName = "IsSupervisor", action = "http://www.nortel.com/soa/oi/cct/AgentService/IsSupervisor")
    public com.nortel.soa.oi.cct.types.agentservice.BooleanResponse isSupervisor(
        @WebParam(partName = "parameters", name = "IsSupervisorRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/AgentService")
        com.nortel.soa.oi.cct.types.agentservice.AgentRequest parameters
    ) throws IsSupervisorException, SessionNotCreatedException;
}
