
package com.nortel.soa.oi.cct.agentservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:25.640+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetAgentsException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetAgentsException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAgentsException;

    public GetAgentsException() {
        super();
    }
    
    public GetAgentsException(String message) {
        super(message);
    }
    
    public GetAgentsException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAgentsException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAgentsException) {
        super(message);
        this.getAgentsException = getAgentsException;
    }

    public GetAgentsException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAgentsException, Throwable cause) {
        super(message, cause);
        this.getAgentsException = getAgentsException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getAgentsException;
    }
}
