
package com.nortel.soa.oi.cct.agentservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:25.640+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetContactTypesException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetContactTypesException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactTypesException;

    public GetContactTypesException() {
        super();
    }
    
    public GetContactTypesException(String message) {
        super(message);
    }
    
    public GetContactTypesException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContactTypesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactTypesException) {
        super(message);
        this.getContactTypesException = getContactTypesException;
    }

    public GetContactTypesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactTypesException, Throwable cause) {
        super(message, cause);
        this.getContactTypesException = getContactTypesException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getContactTypesException;
    }
}
