
package com.nortel.soa.oi.cct.agentservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:25.453+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetSupervisorException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetSupervisorException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getSupervisorException;

    public GetSupervisorException() {
        super();
    }
    
    public GetSupervisorException(String message) {
        super(message);
    }
    
    public GetSupervisorException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetSupervisorException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getSupervisorException) {
        super(message);
        this.getSupervisorException = getSupervisorException;
    }

    public GetSupervisorException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getSupervisorException, Throwable cause) {
        super(message, cause);
        this.getSupervisorException = getSupervisorException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getSupervisorException;
    }
}
