
package com.nortel.soa.oi.cct.agentservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:25.718+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "IsLoggedInException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class IsLoggedInException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo isLoggedInException;

    public IsLoggedInException() {
        super();
    }
    
    public IsLoggedInException(String message) {
        super(message);
    }
    
    public IsLoggedInException(String message, Throwable cause) {
        super(message, cause);
    }

    public IsLoggedInException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo isLoggedInException) {
        super(message);
        this.isLoggedInException = isLoggedInException;
    }

    public IsLoggedInException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo isLoggedInException, Throwable cause) {
        super(message, cause);
        this.isLoggedInException = isLoggedInException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.isLoggedInException;
    }
}
