
package com.nortel.soa.oi.cct.agentservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:25.625+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "RetrieveException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class RetrieveException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo retrieveException;

    public RetrieveException() {
        super();
    }
    
    public RetrieveException(String message) {
        super(message);
    }
    
    public RetrieveException(String message, Throwable cause) {
        super(message, cause);
    }

    public RetrieveException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo retrieveException) {
        super(message);
        this.retrieveException = retrieveException;
    }

    public RetrieveException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo retrieveException, Throwable cause) {
        super(message, cause);
        this.retrieveException = retrieveException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.retrieveException;
    }
}
