
package com.nortel.soa.oi.cct.agentservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:01:25.656+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetSupervisorException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetSupervisorException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setSupervisorException;

    public SetSupervisorException() {
        super();
    }
    
    public SetSupervisorException(String message) {
        super(message);
    }
    
    public SetSupervisorException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetSupervisorException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setSupervisorException) {
        super(message);
        this.setSupervisorException = setSupervisorException;
    }

    public SetSupervisorException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setSupervisorException, Throwable cause) {
        super(message, cause);
        this.setSupervisorException = setSupervisorException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setSupervisorException;
    }
}
