
package com.nortel.soa.oi.cct.terminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:34.562+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "AnswerException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class AnswerException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo answerException;

    public AnswerException() {
        super();
    }
    
    public AnswerException(String message) {
        super(message);
    }
    
    public AnswerException(String message, Throwable cause) {
        super(message, cause);
    }

    public AnswerException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo answerException) {
        super(message);
        this.answerException = answerException;
    }

    public AnswerException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo answerException, Throwable cause) {
        super(message, cause);
        this.answerException = answerException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.answerException;
    }
}
