
package com.nortel.soa.oi.cct.terminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:34.578+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "CompleteConferenceException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class CompleteConferenceException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo completeConferenceException;

    public CompleteConferenceException() {
        super();
    }
    
    public CompleteConferenceException(String message) {
        super(message);
    }
    
    public CompleteConferenceException(String message, Throwable cause) {
        super(message, cause);
    }

    public CompleteConferenceException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo completeConferenceException) {
        super(message);
        this.completeConferenceException = completeConferenceException;
    }

    public CompleteConferenceException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo completeConferenceException, Throwable cause) {
        super(message, cause);
        this.completeConferenceException = completeConferenceException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.completeConferenceException;
    }
}
