
package com.nortel.soa.oi.cct.terminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:34.640+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetContactTypeException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetContactTypeException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactTypeException;

    public GetContactTypeException() {
        super();
    }
    
    public GetContactTypeException(String message) {
        super(message);
    }
    
    public GetContactTypeException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContactTypeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactTypeException) {
        super(message);
        this.getContactTypeException = getContactTypeException;
    }

    public GetContactTypeException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getContactTypeException, Throwable cause) {
        super(message, cause);
        this.getContactTypeException = getContactTypeException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getContactTypeException;
    }
}
