
package com.nortel.soa.oi.cct.terminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:34.656+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetTerminalConnectionCapabilitiesException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetTerminalConnectionCapabilitiesException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalConnectionCapabilitiesException;

    public GetTerminalConnectionCapabilitiesException() {
        super();
    }
    
    public GetTerminalConnectionCapabilitiesException(String message) {
        super(message);
    }
    
    public GetTerminalConnectionCapabilitiesException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTerminalConnectionCapabilitiesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalConnectionCapabilitiesException) {
        super(message);
        this.getTerminalConnectionCapabilitiesException = getTerminalConnectionCapabilitiesException;
    }

    public GetTerminalConnectionCapabilitiesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTerminalConnectionCapabilitiesException, Throwable cause) {
        super(message, cause);
        this.getTerminalConnectionCapabilitiesException = getTerminalConnectionCapabilitiesException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getTerminalConnectionCapabilitiesException;
    }
}
