
package com.nortel.soa.oi.cct.terminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:34.593+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetTransferConsultContactException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetTransferConsultContactException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTransferConsultContactException;

    public GetTransferConsultContactException() {
        super();
    }
    
    public GetTransferConsultContactException(String message) {
        super(message);
    }
    
    public GetTransferConsultContactException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetTransferConsultContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTransferConsultContactException) {
        super(message);
        this.getTransferConsultContactException = getTransferConsultContactException;
    }

    public GetTransferConsultContactException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getTransferConsultContactException, Throwable cause) {
        super(message, cause);
        this.getTransferConsultContactException = getTransferConsultContactException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getTransferConsultContactException;
    }
}
