
package com.nortel.soa.oi.cct.terminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:34.671+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "HoldException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class HoldException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo holdException;

    public HoldException() {
        super();
    }
    
    public HoldException(String message) {
        super(message);
    }
    
    public HoldException(String message, Throwable cause) {
        super(message, cause);
    }

    public HoldException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo holdException) {
        super(message);
        this.holdException = holdException;
    }

    public HoldException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo holdException, Throwable cause) {
        super(message, cause);
        this.holdException = holdException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.holdException;
    }
}
