package com.nortel.soa.oi.cct.terminalconnectionservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:34.703+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService", name = "TerminalConnectionService")
@XmlSeeAlso({com.nortel.soa.oi.cct.faults.ObjectFactory.class, com.nortel.soa.oi.cct.types.terminalconnectionservice.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TerminalConnectionService {

    @WebResult(name = "GetVersionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetVersion", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GetVersion")
    public com.nortel.soa.oi.cct.types.GetVersionResponse getVersion(
        @WebParam(partName = "parameters", name = "GetVersionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.GetVersionRequest parameters
    ) throws GetVersionException, SessionNotCreatedException;

    @WebResult(name = "GetTerminalResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetTerminal", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GetTerminal")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalResponse getTerminal(
        @WebParam(partName = "parameters", name = "GetTerminalRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetTerminalException, SessionNotCreatedException;

    @WebResult(name = "GetStateResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetState", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GetState")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionStateResponse getState(
        @WebParam(partName = "parameters", name = "GetStateRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetStateException, SessionNotCreatedException;

    @WebMethod(operationName = "CompleteSupervisedTransfer", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/CompleteSupervisedTransfer")
    public void completeSupervisedTransfer(
        @WebParam(partName = "parameters", name = "CompleteSupervisedTransferRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionContactRequest parameters
    ) throws CompleteSupervisedTransferException, SessionNotCreatedException;

    @WebMethod(operationName = "Answer", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/Answer")
    public void answer(
        @WebParam(partName = "parameters", name = "AnswerRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws AnswerException, SessionNotCreatedException;

    @WebResult(name = "InitiateSupervisedTransferResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "result")
    @WebMethod(operationName = "InitiateSupervisedTransfer", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/InitiateSupervisedTransfer")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.ContactResponse initiateSupervisedTransfer(
        @WebParam(partName = "parameters", name = "InitiateSupervisedTransferRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionAddressRequest parameters
    ) throws InitiateSupervisedTransferException, SessionNotCreatedException;

    @WebMethod(operationName = "CompleteConference", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/CompleteConference")
    public void completeConference(
        @WebParam(partName = "parameters", name = "CompleteConferenceRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionContactRequest parameters
    ) throws CompleteConferenceException, SessionNotCreatedException;

    @WebResult(name = "GetTransferConsultContactResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetTransferConsultContact", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GetTransferConsultContact")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.ContactResponse getTransferConsultContact(
        @WebParam(partName = "parameters", name = "GetTransferConsultContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetTransferConsultContactException, SessionNotCreatedException;

    @WebMethod(operationName = "GenerateDTMF", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GenerateDTMF")
    public void generateDTMF(
        @WebParam(partName = "parameters", name = "GenerateDTMFRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.GenerateDTMFRequest parameters
    ) throws GenerateDTMFException, SessionNotCreatedException;

    @WebMethod(operationName = "Unhold", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/Unhold")
    public void unhold(
        @WebParam(partName = "parameters", name = "UnholdRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws UnholdException, SessionNotCreatedException;

    @WebResult(name = "GetConferenceConsultContactResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetConferenceConsultContact", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GetConferenceConsultContact")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.ContactResponse getConferenceConsultContact(
        @WebParam(partName = "parameters", name = "GetConferenceConsultContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetConferenceConsultContactException, SessionNotCreatedException;

    @WebResult(name = "ConsultResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "result")
    @WebMethod(operationName = "Consult", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/Consult")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.ContactResponse consult(
        @WebParam(partName = "parameters", name = "ConsultRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.ConsultRequest parameters
    ) throws ConsultException, SessionNotCreatedException;

    @WebMethod(operationName = "BlindTransfer", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/Transfer")
    public void blindTransfer(
        @WebParam(partName = "parameters", name = "BlindTransferRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionAddressRequest parameters
    ) throws TransferException, SessionNotCreatedException;

    @WebResult(name = "GetContactTypeResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetContactType", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GetContactType")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.GetContactTypeResponse getContactType(
        @WebParam(partName = "parameters", name = "GetContactTypeRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetContactTypeException, SessionNotCreatedException;

    @WebResult(name = "InitiateConferenceResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "result")
    @WebMethod(operationName = "InitiateConference", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/InitiateConference")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.ContactResponse initiateConference(
        @WebParam(partName = "parameters", name = "InitiateConferenceRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionAddressRequest parameters
    ) throws InitiateConferenceException, SessionNotCreatedException;

    @WebResult(name = "GetTerminalConnectionCapabilitiesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetTerminalConnectionCapabilities", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GetTerminalConnectionCapabilities")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.GetTerminalConnectionCapabilitiesResponse getTerminalConnectionCapabilities(
        @WebParam(partName = "parameters", name = "GetTerminalConnectionCapabilitiesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetTerminalConnectionCapabilitiesException, SessionNotCreatedException;

    @WebMethod(operationName = "Hold", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/Hold")
    public void hold(
        @WebParam(partName = "parameters", name = "HoldRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws HoldException, SessionNotCreatedException;

    @WebResult(name = "GetConnectionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetConnection", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GetConnection")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.ConnectionResponse getConnection(
        @WebParam(partName = "parameters", name = "GetConnectionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetConnectionException, SessionNotCreatedException;

    @WebResult(name = "GetContactResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetContact", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GetContact")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.ContactResponse getContact(
        @WebParam(partName = "parameters", name = "GetContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetContactException, SessionNotCreatedException;

    @WebResult(name = "GetConsultContactResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService", partName = "response")
    @WebMethod(operationName = "GetConsultContact", action = "http://www.nortel.com/soa/oi/cct/TerminalConnectionService/GetConsultContact")
    public com.nortel.soa.oi.cct.types.terminalconnectionservice.ContactResponse getConsultContact(
        @WebParam(partName = "parameters", name = "GetConsultContactRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/TerminalConnectionService")
        com.nortel.soa.oi.cct.types.terminalconnectionservice.TerminalConnectionRequest parameters
    ) throws GetConsultContactException, SessionNotCreatedException;
}
