
package com.nortel.soa.oi.cct.terminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:34.640+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "TransferException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class TransferException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo transferException;

    public TransferException() {
        super();
    }
    
    public TransferException(String message) {
        super(message);
    }
    
    public TransferException(String message, Throwable cause) {
        super(message, cause);
    }

    public TransferException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo transferException) {
        super(message);
        this.transferException = transferException;
    }

    public TransferException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo transferException, Throwable cause) {
        super(message, cause);
        this.transferException = transferException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.transferException;
    }
}
