
package com.nortel.soa.oi.cct.terminalconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:34.609+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "UnholdException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class UnholdException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo unholdException;

    public UnholdException() {
        super();
    }
    
    public UnholdException(String message) {
        super(message);
    }
    
    public UnholdException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnholdException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo unholdException) {
        super(message);
        this.unholdException = unholdException;
    }

    public UnholdException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo unholdException, Throwable cause) {
        super(message, cause);
        this.unholdException = unholdException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.unholdException;
    }
}
