
package com.nortel.soa.oi.cct.contactservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:44.078+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "AddPartyException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class AddPartyException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo addPartyException;

    public AddPartyException() {
        super();
    }
    
    public AddPartyException(String message) {
        super(message);
    }
    
    public AddPartyException(String message, Throwable cause) {
        super(message, cause);
    }

    public AddPartyException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo addPartyException) {
        super(message);
        this.addPartyException = addPartyException;
    }

    public AddPartyException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo addPartyException, Throwable cause) {
        super(message, cause);
        this.addPartyException = addPartyException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.addPartyException;
    }
}
