
package com.nortel.soa.oi.cct.contactservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:44.265+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetAttachedXMLDataException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetAttachedXMLDataException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAttachedXMLDataException;

    public GetAttachedXMLDataException() {
        super();
    }
    
    public GetAttachedXMLDataException(String message) {
        super(message);
    }
    
    public GetAttachedXMLDataException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAttachedXMLDataException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAttachedXMLDataException) {
        super(message);
        this.getAttachedXMLDataException = getAttachedXMLDataException;
    }

    public GetAttachedXMLDataException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getAttachedXMLDataException, Throwable cause) {
        super(message, cause);
        this.getAttachedXMLDataException = getAttachedXMLDataException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getAttachedXMLDataException;
    }
}
