
package com.nortel.soa.oi.cct.contactservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:44.250+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetCallingTerminalException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetCallingTerminalException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getCallingTerminalException;

    public GetCallingTerminalException() {
        super();
    }
    
    public GetCallingTerminalException(String message) {
        super(message);
    }
    
    public GetCallingTerminalException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetCallingTerminalException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getCallingTerminalException) {
        super(message);
        this.getCallingTerminalException = getCallingTerminalException;
    }

    public GetCallingTerminalException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getCallingTerminalException, Throwable cause) {
        super(message, cause);
        this.getCallingTerminalException = getCallingTerminalException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getCallingTerminalException;
    }
}
