
package com.nortel.soa.oi.cct.contactservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:44.328+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetLastRedirectedAddressException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetLastRedirectedAddressException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getLastRedirectedAddressException;

    public GetLastRedirectedAddressException() {
        super();
    }
    
    public GetLastRedirectedAddressException(String message) {
        super(message);
    }
    
    public GetLastRedirectedAddressException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetLastRedirectedAddressException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getLastRedirectedAddressException) {
        super(message);
        this.getLastRedirectedAddressException = getLastRedirectedAddressException;
    }

    public GetLastRedirectedAddressException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getLastRedirectedAddressException, Throwable cause) {
        super(message, cause);
        this.getLastRedirectedAddressException = getLastRedirectedAddressException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getLastRedirectedAddressException;
    }
}
