
package com.nortel.soa.oi.cct.contactservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:44.109+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GetUUIException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GetUUIException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getUUIException;

    public GetUUIException() {
        super();
    }
    
    public GetUUIException(String message) {
        super(message);
    }
    
    public GetUUIException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetUUIException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getUUIException) {
        super(message);
        this.getUUIException = getUUIException;
    }

    public GetUUIException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getUUIException, Throwable cause) {
        super(message, cause);
        this.getUUIException = getUUIException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.getUUIException;
    }
}
