
package com.nortel.soa.oi.cct.contactservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:44.140+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetInstantMessagesException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetInstantMessagesException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setInstantMessagesException;

    public SetInstantMessagesException() {
        super();
    }
    
    public SetInstantMessagesException(String message) {
        super(message);
    }
    
    public SetInstantMessagesException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetInstantMessagesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setInstantMessagesException) {
        super(message);
        this.setInstantMessagesException = setInstantMessagesException;
    }

    public SetInstantMessagesException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setInstantMessagesException, Throwable cause) {
        super(message, cause);
        this.setInstantMessagesException = setInstantMessagesException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setInstantMessagesException;
    }
}
