
package com.nortel.soa.oi.cct.contactservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:02:44.296+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "SetUUIException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class SetUUIException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setUUIException;

    public SetUUIException() {
        super();
    }
    
    public SetUUIException(String message) {
        super(message);
    }
    
    public SetUUIException(String message, Throwable cause) {
        super(message, cause);
    }

    public SetUUIException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setUUIException) {
        super(message);
        this.setUUIException = setUUIException;
    }

    public SetUUIException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo setUUIException, Throwable cause) {
        super(message, cause);
        this.setUUIException = setUUIException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.setUUIException;
    }
}
