package com.nortel.soa.oi.cct.notificationconsumer;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:05:30.234+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/NotificationConsumer", name = "NotificationConsumer")
@XmlSeeAlso({com.nortel.soa.oi.cct.notification.ObjectFactory.class, com.nortel.soa.oi.cct.types.notificationconsumer.ObjectFactory.class, com.nortel.soa.oi.cct.basenotification.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class})
public interface NotificationConsumer {

    @Oneway
    @RequestWrapper(localName = "Notify", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationConsumer", className = "com.nortel.soa.oi.cct.types.notificationconsumer.Notify")
    @WebMethod(operationName = "Notify", action = "http://www.nortel.com/soa/oi/cct/notificationconsumer/service/Notify")
    public void notify(
        @WebParam(name = "NotificationMessage", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/NotificationConsumer")
        java.util.List<com.nortel.soa.oi.cct.basenotification.NotificationMessageHolderType> notificationMessage
    );
}
