package com.nortel.soa.oi.cct.notificationconsumer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:05:30.250+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "SOAOICCT_NotificationConsumer", 
                  wsdlLocation = "http://ccc-aacc-mgt:9090/NotificationConsumer.wsdl",
                  targetNamespace = "http://www.nortel.com/soa/oi/cct/NotificationConsumer") 
public class SOAOICCTNotificationConsumer extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.nortel.com/soa/oi/cct/NotificationConsumer", "SOAOICCT_NotificationConsumer");
    public final static QName NotificationConsumer = new QName("http://www.nortel.com/soa/oi/cct/NotificationConsumer", "NotificationConsumer");
    static {
        URL url = null;
        try {
            url = new URL("http://ccc-aacc-mgt:9090/NotificationConsumer.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SOAOICCTNotificationConsumer.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ccc-aacc-mgt:9090/NotificationConsumer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SOAOICCTNotificationConsumer(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SOAOICCTNotificationConsumer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAOICCTNotificationConsumer() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAOICCTNotificationConsumer(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAOICCTNotificationConsumer(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAOICCTNotificationConsumer(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NotificationConsumer
     */
    @WebEndpoint(name = "NotificationConsumer")
    public NotificationConsumer getNotificationConsumer() {
        return super.getPort(NotificationConsumer, NotificationConsumer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationConsumer
     */
    @WebEndpoint(name = "NotificationConsumer")
    public NotificationConsumer getNotificationConsumer(WebServiceFeature... features) {
        return super.getPort(NotificationConsumer, NotificationConsumer.class, features);
    }

}
