
package com.nortel.soa.oi.cct.routepointconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:09.390+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "GiveMediaTreatmentException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class GiveMediaTreatmentException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo giveMediaTreatmentException;

    public GiveMediaTreatmentException() {
        super();
    }
    
    public GiveMediaTreatmentException(String message) {
        super(message);
    }
    
    public GiveMediaTreatmentException(String message, Throwable cause) {
        super(message, cause);
    }

    public GiveMediaTreatmentException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo giveMediaTreatmentException) {
        super(message);
        this.giveMediaTreatmentException = giveMediaTreatmentException;
    }

    public GiveMediaTreatmentException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo giveMediaTreatmentException, Throwable cause) {
        super(message, cause);
        this.giveMediaTreatmentException = giveMediaTreatmentException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.giveMediaTreatmentException;
    }
}
