
package com.nortel.soa.oi.cct.routepointconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:09.375+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "RouteException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class RouteException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo routeException;

    public RouteException() {
        super();
    }
    
    public RouteException(String message) {
        super(message);
    }
    
    public RouteException(String message, Throwable cause) {
        super(message, cause);
    }

    public RouteException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo routeException) {
        super(message);
        this.routeException = routeException;
    }

    public RouteException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo routeException, Throwable cause) {
        super(message, cause);
        this.routeException = routeException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.routeException;
    }
}
