
package com.nortel.soa.oi.cct.routepointconnectionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:09.234+03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "RoutePointRetrieveException", targetNamespace = "http://www.nortel.com/soa/oi/cct/faults")
public class RoutePointRetrieveException extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo routePointRetrieveException;

    public RoutePointRetrieveException() {
        super();
    }
    
    public RoutePointRetrieveException(String message) {
        super(message);
    }
    
    public RoutePointRetrieveException(String message, Throwable cause) {
        super(message, cause);
    }

    public RoutePointRetrieveException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo routePointRetrieveException) {
        super(message);
        this.routePointRetrieveException = routePointRetrieveException;
    }

    public RoutePointRetrieveException(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo routePointRetrieveException, Throwable cause) {
        super(message, cause);
        this.routePointRetrieveException = routePointRetrieveException;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ExceptionInfo getFaultInfo() {
        return this.routePointRetrieveException;
    }
}
