package com.nortel.soa.oi.cct.routepointconnectionservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-31T11:04:09.406+03:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.nortel.com/soa/oi/cct/RoutePointConnectionService", name = "RoutePointConnectionService")
@XmlSeeAlso({com.nortel.soa.oi.cct.types.routepointconnectionservice.ObjectFactory.class, com.nortel.soa.oi.cct.faults.ObjectFactory.class, com.nortel.soa.oi.cct.types.ObjectFactory.class, org.xmlsoap.schemas.ws._2003._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RoutePointConnectionService {

    @WebMethod(operationName = "RoutePointRetrieve", action = "http://www.nortel.com/soa/oi/cct/RoutePointConnectionService/RoutePointRetrieve")
    public void routePointRetrieve(
        @WebParam(partName = "parameters", name = "RoutePointRetrieveRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointConnectionService")
        com.nortel.soa.oi.cct.types.routepointconnectionservice.RoutePointRetrieveRequest parameters
    ) throws RoutePointRetrieveException, SessionNotCreatedException;

    @WebResult(name = "GetVersionResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointConnectionService", partName = "response")
    @WebMethod(operationName = "GetVersion", action = "http://www.nortel.com/soa/oi/cct/RoutePointConnectionService/GetVersion")
    public com.nortel.soa.oi.cct.types.GetVersionResponse getVersion(
        @WebParam(partName = "parameters", name = "GetVersionRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointConnectionService")
        com.nortel.soa.oi.cct.types.GetVersionRequest parameters
    ) throws GetVersionException, SessionNotCreatedException;

    @WebResult(name = "GetCapabilitiesResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointConnectionService", partName = "response")
    @WebMethod(operationName = "GetCapabilities", action = "http://www.nortel.com/soa/oi/cct/RoutePointConnectionService/GetCapabilities")
    public com.nortel.soa.oi.cct.types.routepointconnectionservice.ConnectionCapabilitiesResponse getCapabilities(
        @WebParam(partName = "parameters", name = "GetCapabilitiesRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointConnectionService")
        com.nortel.soa.oi.cct.types.routepointconnectionservice.ConnectionRequest parameters
    ) throws GetCapabilitiesException, SessionNotCreatedException;

    @WebResult(name = "RouteResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointConnectionService", partName = "result")
    @WebMethod(operationName = "Route", action = "http://www.nortel.com/soa/oi/cct/RoutePointConnectionService/Route")
    public com.nortel.soa.oi.cct.types.routepointconnectionservice.RouteResponse route(
        @WebParam(partName = "parameters", name = "RouteRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointConnectionService")
        com.nortel.soa.oi.cct.types.routepointconnectionservice.RouteRequest parameters
    ) throws RouteException, SessionNotCreatedException;

    @WebResult(name = "GiveMediaTreatmentResponse", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointConnectionService", partName = "response")
    @WebMethod(operationName = "GiveMediaTreatment", action = "http://www.nortel.com/soa/oi/cct/RoutePointConnectionService/GiveMediaTreatment")
    public com.nortel.soa.oi.cct.types.routepointconnectionservice.GiveMediaTreatmentResponse giveMediaTreatment(
        @WebParam(partName = "parameters", name = "GiveMediaTreatmentRequest", targetNamespace = "http://www.nortel.com/soa/oi/cct/types/RoutePointConnectionService")
        com.nortel.soa.oi.cct.types.routepointconnectionservice.GiveMediaTreatmentRequest parameters
    ) throws GiveMediaTreatmentException, SessionNotCreatedException;
}
